### ISSUE TITLE
Keyboard navigation does not work with layouts other than English

### ISSUE THREAD

**Issue by lue** [mozilla/hubs#2330] opened 2020-04-05 18:50 UTC
**Description**
If my keyboard layout is switched to Russian, WASD keys do not work. It might be the issue with other layouts too.

**To Reproduce**
Switch to Russian keyboard layout. Try to navigate with WASD.

**Expected behavior**
Independent of the keyboard layout WASD buttons should always work.

**Hardware** 
 - Desktop
 - OS: Windows 10
 - Chrome, Edge

**Comment by vincentfretin** [comment] 2020-06-10 07:24
duplicate of #2397

**Comment by misslivirose** [comment] 2020-06-29 21:58
Resolving as duplicate of #2397 - thanks for reporting this!

**Closed by misslivirose** 2020-06-29 21:58 UTC
Labels: P1, bug
