### ISSUE TITLE
'Module not found' error while running npm login

### ISSUE THREAD

**Issue by manasa15M** [mozilla/hubs#5922] opened 2023-01-31 07:55 UTC
Hello Users

I am new to Hubs cloud. I have a working AWS Hubs Cloud instance and am trying to setup the custom client and seeing MODULE_NOT_FOUND error during 'npm run login'. PFB error.

Thank you!

$ npm run login

hubs@0.0.1 login
node -r @babel/register -r esm -r ./scripts/shim scripts/login.js
..
..
..

usr/bin/hubs-master/hubs/src/utils/phoenix-utils.js:1
Error: Cannot find module '../utils/store-instance'
Require stack:
usr/bin/hubs-master/hubs/src/utils/phoenix-utils.js
usr/bin/hubs-master/hubs/src/scripts/login.js
at Object. <anonymous> (usr/bin/hubs-master/hubs/src/utils/ phoenix-utils.js:5:1)
at Generator.next (<anonymous>) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'usr/bin/hubs-master/hubs/src/utils/ phoenix-utils.js',
usr/bin/hubs-master/hubs/src/scripts/login.js

]
}

npm -v
8.11.0
node -v 
16.16.0

sudo yum info nodejs
Loaded plugins: extras_suggestioms, langpacks, priorities, update-motd
Installed Packages
Name : nodejs
Arch : x86_64
Epoch : 2
Version : 12.22.12

Note: "store-instance.ts" is located in 'usr/bin/hubs-master/hubs/src/utils/store-instance.ts'

**Comment by rawnsley** [comment] 2023-01-31 08:49
Duplicate of https://github.com/mozilla/hubs/issues/5897

**Comment by manasa15M** [comment] 2023-01-31 09:27
Hi
Please help me with the solution for this

**Comment by rawnsley** [comment] 2023-01-31 09:34
> phoenix-utils.js

I've added a note to the issue I linked to. I suggest you close this one and add your own experience over there. Issues with weight-of-numbers are more likely to be dealt with first.

**Comment by manasa15M** [comment] 2023-01-31 09:40
Okay

**Closed** 2023-02-15 13:17 UTC
Labels: bug, needs triage
