### ISSUE TITLE
Avatars stay in room after user leaves

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1893] opened 2019-11-12 14:58 UTC
**Description**
Sometimes when users leave a Hubs room, their avatar stays behind. If the user re-joins the room, their old avatar is not visible to them, however, for everyone else in the space they see two of that user

**To Reproduce**
Have not figured out how to reproduce, but occurs fairly often

**Expected behavior**
Expect avatar to leave when user leaves

**Screenshots**
This user left the room but their avatar stayed. There were two when they returned.
<img width="647" alt="Screen Shot 2019-11-08 at 11 55 17 AM" src="https://user-images.githubusercontent.com/6835324/68681969-37fefb00-0519-11ea-9c03-f97f64fad280.png">

**Hardware** 
It happened once with one user when they refreshed the page using Chrome browser on PC, not sure if it has happened on other systems/devices

**Additional context**
We've seen this issue at Hubs meetups, and it was also flagged by community members.

**Comment by misslivirose** [comment] 2019-11-13 19:46
Just saw this today when @robertlong 's browser crashed. The original avatar did "leave" shortly afterwards ('Crested-Shelduck' is the original display name that Robert was using)  

![image](https://user-images.githubusercontent.com/4313320/68798315-0b2b1080-060b-11ea-8692-1bed0f3d0e22.png)

**Comment by gfodor** [comment] 2020-01-06 19:47
I did some preliminary investigation into this and could not reproduce. *However*, it is a known "by-design" issue where if someone's client terminates unexpectedly, the various connection timeouts need to be triggered before their avatar will disappear. (30 seconds) -- so we should confirm when we see this happening if there are instances where the avatar stays permanently visible.

**Comment by emclaren** [comment] 2020-01-08 19:35
I can confirm that many of the times I've seen this happen it has been longer than 30 seconds. I often end up kicking them from the room manually because the avatar seems to be permanently visible.

**Comment by gfodor** [comment] 2020-01-08 20:44
OK thanks. Not sure what that is then. Hmm. If we have a solid way to repro
that'd be the main thing now. I did a bunch of attempts to repro by
shutting computers off, pulling network cables, etc. All the avatars got
cleaned up after 30s.

**Comment by emclaren** [comment] 2020-01-10 14:46
I have also tried to repro this by crashing tabs, closing browsers with no success. I will make a point of trying to gather more information for room visitors when this happens (browser/OS/circumstance)

**Comment by gfodor** [comment] 2020-04-03 04:05
I think I finally have a repro for this - it seems to happen with bots if you open a second browser window and then alt-tab to it while the bots disconnect. If you alt tab back, the avatars are stuck.

**Comment by joshmarinacci** [comment] 2020-07-17 19:44
Can we close this as fixed now that the other items are merged?

**Comment by misslivirose** [comment] 2020-07-17 23:34
The comment in https://github.com/mozilla/naf-janus-adapter/pull/100 mentioned that it was a partial fix, but I don't know that we've continued to see reports of this since that update.

**Comment by joshmarinacci** [comment] 2020-07-17 23:54
If no one else has seen it let's close for now

**Closed** 2020-07-18 00:47 UTC
Labels: P1, bug
