### ISSUE TITLE
[New UI] The “!” sign is shown at first when creating a react emoji

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [mozilla/hubs#3357] opened 2020-11-17 12:11 UTC
**[Affected Versions]:**
- Firefox Release 82.0.3
- Chrome 86.0.4240.198

**[Affected Platforms]:**
- Windows 10x64

**[Prerequisites]:**
- Have a new room created and entered.

**[Steps to reproduce]:**
1. Click the “React” button from the bottom menu.
2. Click one of the react emojis.
3. Observe the top of the emoji created.

**[Expected results]:**
- The react emoji is displayed and smaller emojis are being generated from the top.

**[Actual results]:**
- The react emoji is displayed and “!” signs are being generated from the top.

**[Notes]:**
- After a few seconds the correct emojis are generated from the top.
- Attached a screen recording of the issue below.
![react_emoji](https://user-images.githubusercontent.com/51400741/99388628-8d18de00-28de-11eb-9b30-a4b1f6dee3dc.gif)

**Comment by rawnsley** [comment] 2021-03-29 13:06
This is happening for me in Chrome on MacOS. It looks like a CORS error. Here's the developer console output:

Access to fetch at 'https://assets-prod.reticulum.io/hubs/assets/images/emojis/emoji_3-c6f4eb89cc99bcb1977111cb56905e9c.png' from origin 'https://hubs.mozilla.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
raven.js:1475 GET https://assets-prod.reticulum.io/hubs/assets/images/emojis/emoji_3-c6f4eb89cc99bcb1977111cb56905e9c.png net::ERR_FAILED
(anonymous) @ raven.js:1475
load @ three.module.js:41888
(anonymous) @ HubsTextureLoader.js:2
(anonymous) @ HubsTextureLoader.js:2
i @ HubsTextureLoader.js:39
a @ hub-05ccffcbb2e27e47ddae.js:1
s @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
loadTextureAsync @ hub-05ccffcbb2e27e47ddae.js:1
n @ particle-emitter.js:62
he @ hub-05ccffcbb2e27e47ddae.js:1
o @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
setTexture @ hub-05ccffcbb2e27e47ddae.js:1
update @ particle-emitter.js:79
callUpdateHandler @ component.js:419
updateProperties @ component.js:300
value @ a-entity.js:490
Object.create.setAttribute.value @ a-entity.js:727
(anonymous) @ emoji.js:57
a @ raven.js:377
e.exports.Object.create.emit.value @ a-node.js:263
(anonymous) @ gltf-model-plus.js:620
p @ hub-05ccffcbb2e27e47ddae.js:1
o @ hub-05ccffcbb2e27e47ddae.js:1
Promise.then (async)
p @ hub-05ccffcbb2e27e47ddae.js:1
o @ hub-05ccffcbb2e27e47ddae.js:1
Promise.then (async)
p @ hub-05ccffcbb2e27e47ddae.js:1
o @ hub-05ccffcbb2e27e47ddae.js:1
Promise.then (async)
p @ hub-05ccffcbb2e27e47ddae.js:1
o @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
applySrc @ gltf-model-plus.js:524
update @ gltf-model-plus.js:503
initComponent @ component.js:330
updateProperties @ component.js:302
e.exports.Component @ component.js:78
n @ component.js:662
value @ a-entity.js:332
value @ a-entity.js:495
Object.create.setAttribute.value @ a-entity.js:727
(anonymous) @ media-loader.js:567
v @ hub-05ccffcbb2e27e47ddae.js:1
o @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
(anonymous) @ hub-05ccffcbb2e27e47ddae.js:1
update @ media-loader.js:329
initComponent @ component.js:330
updateProperties @ component.js:302
value @ a-entity.js:490
value @ a-entity.js:463
(anonymous) @ a-entity.js:249
(anonymous) @ a-node.js:127
Promise.then (async)
value @ a-node.js:125
value @ a-entity.js:245
value @ a-entity.js:88
value @ a-register-element.js:160
m @ document-register-element.js:2
(anonymous) @ document-register-element.js:2
n @ document-register-element.js:2
(anonymous) @ document-register-element.js:2
attributes (async)
value @ a-entity.js:341
value @ a-entity.js:495
Object.create.setAttribute.value @ a-entity.js:727
O @ media-utils.js:160
fe @ emoji.js:51
onClick @ ImageGridPopover.js:17
u @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
v @ react-dom.production.min.js:15
ot @ react-dom.production.min.js:52
at @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
I @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
Xt @ react-dom.production.min.js:70
Yt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Ha @ react-dom.production.min.js:122
M @ react-dom.production.min.js:287
Gt @ react-dom.production.min.js:68
a @ raven.js:377
console.js:35 TypeError: Failed to fetch

**Comment by takahirox** [comment] 2021-06-11 00:53
Somehow the problem has been resolved on my Windows10 + Firefox Nightly.

![image](https://user-images.githubusercontent.com/7637832/121614829-6bb34700-ca14-11eb-94fb-6b0388053d40.png)

But I still see the error on my Windows10 + Chrome. "!" signs or small emoji even doesn't appear now.

![image](https://user-images.githubusercontent.com/7637832/121614882-88e81580-ca14-11eb-9473-53891e7414ca.png)

Tested at https://hubs.mozilla.com/

**Comment by takahirox** [comment] 2021-06-25 00:53
I'm investigating "small emojis are not rendered" problem on Chrome https://github.com/mozilla/hubs/issues/3357#issuecomment-859182129

I noticed that they are rendered if I disable network cache in Chrome devtool network tab. Can anyone here try the same test to check if you can reproduce?
1. Go to hubs.mozilla.com and enter a room on Chrome.
2. Click React and emojis, and confirm that small emojis are not rendered due to CORS error
3. Check "disable cache" in the devtool network tab
4. Click React and emojis again and confirm that small emojis are rendered

And if you can reproduce, may this be a Chrome bug?

**Comment by takahirox** [comment] 2021-08-02 18:34
The problem on Chrome that emoji are not rendered has been fixed by #4400 but I realized that it's a different problem from the issue mentioned in the issue comment.

I tested emojis again on hubs.mozilla.com and didn't encounter the problem in both Chrome and Firefox.

I guess the "!" sign is a kind of loading sign, similar to loading cube, isn't it? /cc @netpro2k @brianpeiris Small emojis and emoji icons in the "React" dialog refer to the same emoji images. Users first open the "React" dialog, click one of the emoji icons, and then emojis are rendered in the 3D scene.

The emoji image files should be cached in the disk when they open the "React" dialog and the image files should be immediately ready when they click the icon. So it makes sense to me that I don't encounter the "!" icon problem.

@Softvision-GeluHaiduc Would you please test again if you still face the problem?

**Comment by takahirox** [comment] 2021-08-03 18:17
@Softvision-RemusDranca Thank for the test! You no longer see "!" sign? If you don't see "!" sign anymore, let's close this issue. And please reopen if you encouter "!" sign problem again.

**Comment by Softvision-RemusDranca** [comment] 2021-08-05 14:20
The "!" signs are no longer displayed on the mentioned devices. I'll close this issue as verified-fixed.

**Closed by Softvision-RemusDranca** 2021-08-05 14:20 UTC
Labels: P2, [QA]:Minor issue, bug, redesign
