### ISSUE TITLE
There is no recording spawned when using the record function of the “Camera”

### ISSUE THREAD

**Issue by SV-AndreiC** [mozilla/hubs#4922] opened 2021-12-10 12:48 UTC
**[Affected Versions]:**
- Firefox Release 92.01
- Chrome 94.0.4606.61
- Safari 15.1

**[Affected Platforms]:**
- Windows 10x64
- iOS15.1

**[Prerequisites]:**
- The Hubs Cloud stack is set up. 
- Have a room created and opened in Hubs Cloud.

**[Steps to reproduce]:**
1. Tap on the "Camera" button from the Place menu.
2. Tap on the "Video" button.
3. Wait for the recording to finish and observe the outcome.

**[Expected results]:**
- A video object containing the recording spawns in the room.

**[Actual results]:**
- There is no object containing the recording, spawned in the room.

**[Notes]:**
- There is no notification or error message received when the recording finishes.
- If there’s another user in the room a “Broken media link” can be seen spawning in the room. 
- Link to a screen recording of the issue:
https://drive.google.com/file/d/16v_-bKjd4gyTTVWkXbfbRAELmlhyRB_w/view?usp=sharing

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1206)

**Comment by brianpeiris** [comment] 2022-01-14 21:46
Closing this as a duplicate of #4895, since they have the same root cause.

**Comment by brianpeiris** [comment] 2022-01-14 21:46
Actually, I'll keep it open so the QA team can verify it themselves.

**Comment by brianpeiris** [comment] 2022-03-18 00:03
The SpeelyCaptor and the CloudFormation template updates were deployed, and this is currently working on Hubs Cloud, so we can call this closed.

**Closed by brianpeiris** 2022-03-18 00:03 UTC
Labels: bug, needs triage, [QA]:Major-issue, jira-hubs, [QA]:Regression, HC-October-Release
