### ISSUE TITLE
Make Emoji Spawners Customizable

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#3215] opened 2020-10-23 22:19 UTC
We've had people request that the emoji spawners could be customizable (e.g. https://twitter.com/morionart/status/1318794396230451200) - and we have also seen custom emojis seen multiple Hubs Cloud instances. 

It would be neat if people could upload their own custom emojis without having to set up a full Hubs Cloud instance.

**Comment by misslivirose** [comment] 2021-02-01 19:46
Duplicate of #2399

**Closed by misslivirose** 2021-02-01 19:46 UTC
Labels: enhancement
