### ISSUE TITLE
UI crashes when going back through Fast Room Swiching

### ISSUE THREAD

**Issue by Pattersonbl2** [mozilla/hubs#5636] opened 2022-08-04 19:18 UTC
### Discussed in https://github.com/mozilla/hubs/discussions/5635

<div type='discussions-op-text'>

<sup>Originally posted by **leonardoazzi** August  4, 2022</sup>
Hello my beloved community,

Since I merged the HC August update, I'm facing a crash with fast room switching. 
In my instance (merged with hubs-cloud), when I go to a room through a portal (fast room switching) and then I try to go to another one, the UI crashes. 
I know the feature is still experimental, but I could't reproduce the issue in hubs.mozilla.com (master). It works just as it should.
So, is there a fix to this issue not released to hubs-cloud yet?

![e7d80b13-a221-4502-a3d8-4caa5123ccaa](https://user-images.githubusercontent.com/13557537/182840582-60812d2e-9bb2-4e88-8a5d-7be7a85e43e5.png)

Thanks :)</div>

**Comment by rawnsley** [comment] 2022-08-09 16:07
I've definitely seen this problem on our Hubs Cloud and it is very likely to be a problem on Mozilla Hubs as well. You can usually reproduce it by making a sequence of three or more rooms that are linked, going to the end room and then pressing back a few times quickly.

The main cause is reentrancy in the `changeHub` function, which [we have addressed with a psudeo mutex](https://github.com/LearnHub/hubs/commit/38cad3bd15d440c6f86c28bcae54c53bfc3de1c0). I'm not familiar enough with threading in Javascript to know if this is a robust solution.

I recommend that @Pattersonbl2 share a reliable reproduce on Mozilla Hubs. Without that I doubt a PR would be accepted even if I submitted one.

**Comment by Pattersonbl2** [comment] 2022-08-09 18:03
> I've definitely seen this problem on our Hubs Cloud and it is very likely to be a problem on Mozilla Hubs as well. You can usually reproduce it by making a sequence of three or more rooms that are linked, going to the end room and then pressing back a few times quickly.
> 
> The main cause is reentrancy in the `changeHub` function, which [we have addressed with a psudeo mutex](https://github.com/LearnHub/hubs/commit/38cad3bd15d440c6f86c28bcae54c53bfc3de1c0). I'm not familiar enough with threading in Javascript to know if this is a robust solution.
> 
> I recommend that @Pattersonbl2 share a reliable reproduction on Mozilla Hubs. Without that I doubt a PR would be accepted even if I submitted one.

This was a user-submitted issue from a GitHub discussion.  if you could please add your reproduction steps and a pr for a possible fix that would be greatly appreciated.    We had our QA team with the information given from the discussion test this but haven't been able to reproduce this issue.

**Comment by leonardoazzi** [comment] 2022-08-09 20:14
@SV-AndreiC @Pattersonbl2 @rawnsley Thanks for your consideration. I've opened a discussion because I was in doubt if it was a known/duplicate issue or not. @Pattersonbl2 was very helpful and opened this issue for me, but certainly I should describe for you the steps to reproduce as soon as I can.
I've seen this behavior after I merged the hubs-cloud august update with my custom code, both in localhost and in my deployed client. But I'll try to isolate the issue testing just with the hubs-cloud branch.
Thanks again for your attention!

**Comment by rawnsley** [comment] 2022-08-10 09:24
@Pattersonbl2 Sorry - I didn't read the small print closely enough!

You can reproduce the problem if you start [from this room](https://hubs.mozilla.com/z7J9foR/easygoing-used-huddle), follow the link to the next room, then follow the link back to the original room. Do this a few times taking care to let the room load completely, then press back two or three times in quick succession. This should trigger the bug.

If you click through the links before the room has completely loaded, I think another more subtle version of the bug is triggered in which the room appears to have changed, but the scene file has not.

**Comment by leonardoazzi** [comment] 2022-08-11 16:25
Hello everyone,

I studied the issue and I actually introduced this behaviour in my custom code. I was trying to dispatch a "loading" message in change-hub.js , but in the wrong place and with the wrong type. 
![image](https://user-images.githubusercontent.com/13557537/184181198-a3ef4b10-d67d-4d24-837c-628ba6b8c8b1.png)

Now I've tested and created a proper type for this "hub-changing" state. I think it is useful, as a lot of users get lost when they click a portal and the fast room switch fades out of nothing. Also implemented @rawnsley solution to prevent crash (thanks!).
![image](https://user-images.githubusercontent.com/13557537/184181990-21d5b11a-a54d-4a2a-8492-cd3dd5c88a17.png)
![image](https://user-images.githubusercontent.com/13557537/184182067-c7e4a736-59cc-4f00-a3fa-639b739b9edc.png)

I started this conversation opening a discussion and writing in discord instead of opening an issue. I was not sure if it was a problem from the base code or from my custom code. However I think it an important discussion was opened with @rawnsley 's report and @Pattersonbl2 great support.

Thanks for your attention and dedication, as always!

**Comment by emclaren** [comment] 2022-08-16 23:06
Sounds like this issue is closed. Thanks everyone here for your insight and support!

**Closed by emclaren** 2022-08-16 23:06 UTC

**Comment by scrappymeals** [comment] 2022-09-27 00:12
Greetings and I hope everyone is well. I am still experiencing this issue. 

Apologies if I missed a resolution. 

Crash happens after trying to fast room switch more than once.

Thank you and I wish you the best with your projects,
Damon
