### ISSUE TITLE
Media scales when smashing Play-Button or Next-Button multiple times

### ISSUE THREAD

**Issue by PaintedShepherd** [mozilla/hubs#3961] opened 2021-02-25 14:26 UTC
**Description**
When you press the Play-Button of a Video or the next-button of a pdf, then the scale of the media-entity is going bigger. this happens when the media is pinned and you press the button very fast.

**To Reproduce**
1. pin a media-object like a video or a pdf
2. press the a button like play/pause or next/previous
3. the media scales up

**Expected behavior**
the scale animation should be finished, before the next animation can start.

**Screenshots**

**Hardware** 
 - PC 
 - Microsoft Windows 10
 - Google Chrome

**Additional context**

**Comment by misslivirose** [comment] 2021-02-25 15:48
Thanks @PaintedShepherd for filing and sharing that this is also something happening with videos - this is a duplicate of #2284, so I'm going to close this one.

**Closed by misslivirose** 2021-02-25 15:48 UTC
Labels: bug, needs triage
