### ISSUE TITLE
Unable to walk around in spectator mode

### ISSUE THREAD

**Issue by yondr-luka** [mozilla/hubs#5875] opened 2023-01-03 11:15 UTC
**Description**
Unable to walk around when using spectator mode

**To Reproduce**
Click on spectate
![image](https://user-images.githubusercontent.com/93581121/210346743-e719301d-5c0e-4826-96b9-eb417056097e.png)
Using WASD to walk around

**Expected behavior**
Character movement

**Comment by hrithikwins** [comment] 2023-01-05 02:03
Hii @yondr-luka this is not possible in Spectate Mode,
Spectate mode is only for you to listen to other people's audio, if you want to control what spectators wish to see, then your host need to start 'Streaming mode' for the spectators,

I believe you might come across some more questions, so here's a thread you can follow on our discord community for hubs

https://discord.com/channels/498741086295031808/819188464145924117/967042768373420032

**Comment by hrithikwins** [comment] 2023-01-05 02:27
Additionally you can close this issue as this is not a bug

**Closed** 2023-01-05 04:32 UTC
Labels: bug, needs triage

**Comment by yondr-luka** [comment] 2023-01-06 07:56
@hrithikwins I know that 'streaming mode' is a way of sharing a screen to the spectators. But in older video of Mozilla hubs, you can see that you are able to walk around in the room in this mode. Like I remember to do in previous versions of our world.

This feature has been replaced by the Streaming mode?

PS: I am unable to join the discord channel for some reason.

**Comment by matthewbcool** [comment] 2023-01-06 17:32
https://discord.gg/hubs-498741086295031808

@yondr-luka could you please reach out to me via email -  mcool AT mozilla.com with more info about joining discord issues? 
in the mean time you can try the invite above. Thank you!

**Comment by hrithikwins** [comment] 2023-01-07 05:52
Yeah @yondr-luka that thing which you're searching for is different, it's called Lobby Ghosts

For that you should go to your personal hubs admin to do it

Go to App Settings > Features > Lobby Ghosts


Although spectator mode now has camera controls which wasn't earlier...
