### ISSUE TITLE
Null physics body data when rapidly spawning emojis

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#2269] opened 2020-03-22 18:36 UTC
Brian guards against an issue that would otherwise stall the app in this PR: https://github.com/mozilla/hubs/pull/2268
We should figure out what's causing the physics body data to be `null` in the first place or, if it is expected, adjust the code that uses the body data to account for it being sometimes `null`.

**Comment by brianpeiris** [comment] 2020-03-22 19:16
Thanks for filing this. One side effect of my fix might be that emojis get stuck to your hand (thankfully they do disappear) or they fail to grab occasionally. This is not easily reproducible though unless you really try to spam the emojis.

**Comment by InfiniteLee** [comment] 2020-03-22 20:33
So I believe this occurs because collision information is delayed by 1 frame due to the worker.
When object A (the emoji) is deleted, everything about it is cleaned up on the main thread immediately. However, object B (your hand) has a collisions list on it that may include object A and won't get updated until the next time the physics system syncs with the physics worker (the next frame). Thus, for that frame, object B still thinks its colliding with object A, but when we try to grab object A, it's not present anymore.
The fix for this would probably require: on deletion of an object, loop over every other physics object's collision list to remove any references to itself. (Maybe have to build an additional mapping to make this search faster).

**Comment by brianpeiris** [comment] 2020-03-23 18:43
Thanks for the explanation. If #2268 is sufficient for now, I think I'll call this issue closed.

**Closed by brianpeiris** 2020-03-23 18:43 UTC
Labels: tech debt
