### ISSUE TITLE
hub.link URLs show "open link" instead of "visit room"

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#3975] opened 2021-02-28 18:41 UTC
When you paste a link into a hubs room, if i is a long url (e.g. https://hubs.mozilla.com/JmbvjP6) it shows up as "visit room".

If it is a short url (e.g. https://hub.link/JmbvjP6) it shows up as "open link" 

We've heard from a few community members asking why this happens
 
**hubs.mozilla.com url**
<img width="974" alt="Screen Shot 2021-02-28 at 10 38 23 AM" src="https://user-images.githubusercontent.com/6835324/109429601-552b3780-79b1-11eb-9b1e-9353f27b4e7b.png">

**hub.link url**
<img width="586" alt="Screen Shot 2021-02-28 at 10 38 27 AM" src="https://user-images.githubusercontent.com/6835324/109429600-52304700-79b1-11eb-9142-10d1344b94b6.png">

**Comment by misslivirose** [comment] 2021-03-01 14:09
Thanks Elgin, this is a dupe of #3224 so I'm going to resolve this one.

**Closed by misslivirose** 2021-03-01 14:09 UTC
Labels: P2, bug
