### ISSUE TITLE
Allow users to close the "You are muted" message

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#2249] opened 2020-03-20 04:21 UTC
**Is your feature request related to a problem? Please describe.**
A number of members of the community have mentioned the pop up warning them they are muted obscures their view of the room and they wish to close it. 

Most recently it was mentioned by a user at the a11y meetup who mentioned that this popup obscured the view of the captions at the top of the screen. 

<img width="434" alt="Screen Shot 2020-03-19 at 9 06 21 PM" src="https://user-images.githubusercontent.com/6835324/77135096-30031a80-6a27-11ea-8b1a-f707aad1a5a7.png">

**Describe the solution you'd like**
It would be nice to be able to close out of this pop up message

**Comment by misslivirose** [comment] 2020-03-23 14:48
Duplicate of #1140 - I'm going to add the accessibility label to that and bump it up to a P1

**Closed by misslivirose** 2020-03-23 14:48 UTC
Labels: accessibility, enhancement
