### ISSUE TITLE
Display Name - requirements needs to be shown in proper understandable way

### ISSUE THREAD

**Issue by mMARUF** [mozilla/hubs#5687] opened 2022-08-29 21:37 UTC
**OS:**
macOS Monterey version: 12.5.1

**Browser:**
Chrome Version 104.0.5112.101

**Steps to Reproduce:**
1) Go to https://hubs.mozilla.com/
2) Try changing the **Display Name** 

**Actual Result:**
The Display Name requirements are not shown in a proper way. Also the language needs to be more understandable.

**Expected Result:**
The Display Name requirements needs to be shown in a proper way so that it can be understandable to the user.

For Example:

- Alphanumerics, hyphens, underscores, and tildes are accepted 
- At least 3 characters needed
- No more than 32 characters are accepted 

**Attachments:**

<img width="430" alt="Screenshot 2022-08-30 at 3 35 55 AM" src="https://user-images.githubusercontent.com/45368054/187303734-72ee243e-2727-427c-b503-9ece3aaaf11a.png">

**Comment by matthewbcool** [comment] 2022-08-30 19:38
Since "_shown in a proper way so that it can be understandable to the user_" is subjective, I suggest making a feature request where you can leave this as UX feedback. Closing this because it's not a bug. Welcome you to create a feature request instead. Thank you.

**Closed by matthewbcool** 2022-08-30 19:38 UTC
Labels: bug, needs triage
