### ISSUE TITLE
Have deleted Hubs rooms to not display in the list anymore

### ISSUE THREAD

**Issue by youngchief-btw** [mozilla/hubs#2214] opened 2020-03-12 20:35 UTC
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like a way to have my deleted Hubs rooms, not show on my list of rooms anymore

**Describe alternatives you've considered**
I've considered running my own client and server instances and edit the code for it

**Additional context**
N/A

**Comment by misslivirose** [comment] 2020-03-24 15:38
Is this the 'Favorites' list? Curious if this is a dupe of #2148

**Comment by youngchief-btw** [comment] 2020-03-24 22:23
Haven't seen if it happens with non-favs, could be the issue

**Comment by youngchief-btw** [comment] 2020-03-24 22:30
Just confirmed it, It was a 'Favorites' only issue

**Comment by misslivirose** [comment] 2020-03-24 23:40
Thanks for confirming! Going to resolve this as a duplicate of #2148 - we appreciate you filing this!

**Closed by misslivirose** 2020-03-24 23:40 UTC
Labels: enhancement
