### ISSUE TITLE
Race condition on position-at-box-shape-border on selector .paging-toolbar

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1734] opened 2019-09-06 18:38 UTC
`Race condition on position-at-box-shape-border on selector .paging-toolbar`
spammed my console during meetup

**Comment by misslivirose** [comment] 2019-09-06 19:58
Resolving as a dupe of #1741 even though this one was older since someone is already assigned to that one. Thanks for the prompt reporting!

**Closed by misslivirose** 2019-09-06 19:58 UTC
Labels: bug, needs triage
