### ISSUE TITLE
Req Individual one on one chat 

### ISSUE THREAD

**Issue by doreai** [mozilla/hubs#3182] opened 2020-10-16 08:24 UTC
How to implement one on one private chat? is that any code integration is available for an individual private chat inside the room

**Comment by camelgod** [comment] 2020-10-26 20:50
You can follow discussion here: duplicate of https://github.com/mozilla/hubs/issues/2961
No good way to do this yet afaik.

**Comment by truedat101** [comment] 2020-10-27 00:47
For the op, is this voice chat or text chat?  Both are desirable features.

**Comment by misslivirose** [comment] 2021-01-06 18:59
Closing this as a duplicate of #2961. We also have a number of other issues that speak to a desire for a feature that would allow for private voice chat / "Whisper" type functionality.

**Closed by misslivirose** 2021-01-06 18:59 UTC
Labels: enhancement
