### ISSUE TITLE
MacOS Safari: Strange Echo after a few minutes of using

### ISSUE THREAD

**Issue by Yannick1805** [mozilla/hubs#4288] opened 2021-05-25 13:51 UTC
**Description**
When I am entering a room in HUBS inside Safari, the first 2-5 Minutes are working. After this time, a strange sound of echoing starts and I only can get rid of it when I refresh the browser. I also have the issue that I have to manually select my MacBook Air Microphone as standard mic. The same issue is also while I am connected with my AirPods Pro´s.

Inside Chrome and Firefox, everything works normal and the standard mic is also already selected (same with the AirPods)

**To Reproduce**
1. Go to a room
2. Start talking to someone
3. After a few minutes the sound problem should appear

**Screenshots**
attached are two videos. The first one is my view, the second one is the view from my friend. These are WeTransfer Links.

[Video_1](https://wetransfer.com/downloads/ecbd47b178cd314de009540f4f5ca55e20210525134802/f23a1e77942bc01297f65d0bc77148a920210525134901/a87d8d)
[Video_2](https://wetransfer.com/downloads/28a2c18fadd511f69de865edf55b2a8d20210525134919/253a85baeb820c2d9ed3c8d7aa8118bd20210525135002/473af9)

**Hardware** 
 - Device: MacBook Air, M1, 2020
 - OS: macOS Big Sur Version 11.3.1
 - Browser: Safari Version 14.1 (16611.1.21.161.6)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-119)

**Comment by Yannick1805** [comment] 2021-07-13 17:24
Does no one has this issue too?

**Comment by takahirox** [comment] 2021-09-29 22:23
Sounds like this issue is same as #4411

We applied the patch. Would you mind if testing again to check if the problem is still reproducible?

**Comment by brianpeiris** [comment] 2022-04-08 23:08
This is not currently an issue. I've tested to confirm that Safari audio does not distort on macOS. This is primarily due to us disabling Positional audio with #4594, though it seems like the underlying browser issue is fixed now, so we could re-enable positional audio on macOS Safari, but that is a separate from this issue, so I will close this one.

**Closed by brianpeiris** 2022-04-08 23:08 UTC
Labels: bug, P1, needs triage, jira-hubs, safari
