### ISSUE TITLE
Pinned objects reposition when its master leaves on custom spoke scene

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [mozilla/hubs#769] opened 2018-11-29 22:16 UTC
On this [custom scene](https://hub.link/CrsBL06) created with Spoke, pinned videos, objects and images disappear when it's master leaves the room.

Also the option to pin only appears when you move to certain part (the middle part) of the model.

**Comment by gfodor** [comment] 2018-11-30 01:49
The pin menu issue should be fixed once this goes out: https://github.com/mozilla/hubs/pull/768

**Comment by brianpeiris** [comment] 2019-01-01 01:20
I'm unable to reproduce the issue with pinned objects repositioning/disappearing. It may have been fixed with recent updates. Please let us know if you're still experiencing the issue.

**Comment by gfodor** [comment] 2019-02-14 16:06
going to close for now

**Closed by gfodor** 2019-02-14 16:06 UTC
Labels: bug, user submitted

**Comment by mauriciomartinez-itesm** [comment] 2019-02-14 16:07
it hasn't happening anymore
