### ISSUE TITLE
Leading Zero omitted from 6 digit room link code when using VR

### ISSUE THREAD

**Issue by goatchurchprime** [mozilla/hubs#3846] opened 2021-02-02 11:25 UTC
**Description**
If the room number is less than 100000 then when you hit menu and "invite" the room code number is only 5 digits long.  Then when someone types it in to the hubs.link keypad nothing happens.  

It took me a while to work out that I needed to add the extra zero at the front.

**To Reproduce**
See above

**Expected behavior**
The room code number needs to be formatted to include the leading zeros, or never be less than 100000

**Screenshots**
N/A

**Hardware**
 - Device: Quest2
 - OS: Android
 - Browser: default
  
 **Additional context**
N/A

**Comment by misslivirose** [comment] 2021-02-02 14:05
Thanks for the report! This is a duplicate of #3800 and we have a PR open to fix it which should land soon.

**Closed by misslivirose** 2021-02-02 14:05 UTC
Labels: bug, needs triage

**Comment by goatchurchprime** [comment] 2021-02-02 15:08
I looked but didn't find it.  Hopefully my title will contribute to a new search term for that bug.
