### ISSUE TITLE
Test bots move slowly

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#5424] opened 2022-05-11 17:31 UTC
**Description**
The bots we use to test things appear to move in a very choppy manner. It's possible they are doing more processing than before, which taxes the machine they run on. More investigation is required.

**Comment by takahirox** [comment] 2022-07-22 16:43
The problem seems to be caused by our AWS EC servers unexpected high load. We have terminated the test bots running on the server and we will run the bots from the local so far.

We may need to think better bots spawning and/or how to avoid such unexpected high load, but closing this issue because at least it isn't a Hubs Client bug.

**Closed by takahirox** 2022-07-22 16:43 UTC
Labels: bug, P2
