### ISSUE TITLE
Page indices are always 'zero'

### ISSUE THREAD

**Issue by broehl** [mozilla/hubs#2262] opened 2020-03-21 02:09 UTC
In the avatar browser, you can move between pages by clicking on the arrows. In between the arrows, there's a zero. It's always zero, no matter what page you're on.

I suspect that's not what's intended.

**Comment by misslivirose** [comment] 2020-03-23 14:34
Seems to be a pagination issue in general, thanks for filing!

**Comment by misslivirose** [comment] 2020-04-21 21:42
Closing this as a duplicate of #2396

**Closed by misslivirose** 2020-04-21 21:42 UTC
Labels: P2, bug
