### ISSUE TITLE
Disabling 'Create and move objects' in room settings prevents mobile users from interacting with media

### ISSUE THREAD

**Issue by dprado75** [mozilla/hubs#3242] opened 2020-10-28 18:47 UTC
**Description**
Hubs mobile support is limited due to many factores like OS and model. The present behavior for links and media over mobile phones is confusing for both users and creators and, is not the same behavior over desktop or VR (tested using Firefox Reality + Quest).

**To Reproduce**
1. Go to Spoke
2. Create a new Spoke Project. Add a video (default video will do it) and a link to another room.
3. Publish it as a new scene
4. Open a new room with the new scene
5. Test the video controls and room link using a Computer.
6. Test the video controls and room link using a mobile phone.
7. User should be able to play/pause the video, skip it or change its volume and open the link.
8. Go to Room Settings and disable "Create and move objects" in Room Member Permissions
9. Repeat steps 5 and 6. Mobile phone will not allow the users to control the media or use the link.

**Expected behavior**
The above steps demonstrates how the sames features do not work as expect using mobile devices.
It should either have another permission setting for "Enable guest interaction and navigation" (which seems more reasonable) or implement the same behaviour on Desktop devices.

**Hardware** 
 - Device: phone
 - OS: Android / iOS
 - Browser: Chrome / Safari

**Additional context**
For developers working on a custom client, a workaround might be hiding the "spawn / create" element in the top menu UI.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-452)

**Comment by misslivirose** [comment] 2020-11-09 15:19
Hey @dprado75 , this looks like a duplicate of https://github.com/mozilla/hubs/issues/2163 - basically, this happens because the phone browser treats the link as a popup and blocks it. Can you try the workaround in there?

**Comment by dprado75** [comment] 2020-11-10 19:34
> Hey @dprado75 , this looks like a duplicate of #2163 - basically, this happens because the phone browser treats the link as a popup and blocks it. Can you try the workaround in there?

Hi Liv, thanks! 

It's not browser related, it's by design. Please see the whole steps to reproduce as it doesn't involve anything other than changing the room's setting for the links to work on mobile. As you pointed in ticket #2163 there's a comment by jessicasymons   [https://github.com/mozilla/hubs/issues/2163#issuecomment-703541886](url) but it wasn't detailed and since this has been confusing for so long I think it needs to be reviewed. If not, I hope this post will help in the future for users with the same issues.
See tickets:
#2163 
#3066 
#2523
#2098


I've selected a few messages over the Discord server (but there are many more):
https://discordapp.com/channels/498741086295031808/535638855643299840/750358284690653267
https://discordapp.com/channels/498741086295031808/535638724785078292/749191333645647902
https://discordapp.com/channels/498741086295031808/715710114438447114/725639138749054997

**Comment by takahirox** [comment] 2021-10-14 22:40
Should be fixed by #4740

**Closed by takahirox** 2021-10-14 22:40 UTC
Labels: bug, P2, ios, jira-hubs, android
