### ISSUE TITLE
Video playback is choppy in Chrome on macOS

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/hubs#1410] opened 2019-06-05 16:46 UTC
Not sure why Chrome is particularly affected. Video playback is fine in Firefox and Safari on macOS.

**Comment by gfodor** [comment] 2019-08-22 20:51
can't repro, have a test room?

**Comment by brianpeiris** [comment] 2019-12-18 21:30
Repros with https://www.youtube.com/watch?v=0vnA_KIojLg
Video freezes on a frame every few seconds but the audio continues to play.
Repos on a 2018 Macbook Pro, Intel 655 graphics, in Chrome only.

**Comment by brianpeiris** [comment] 2019-12-19 05:02
This seems to be a browser bug. It repros with a simple model-viewer example (which is based on three.js). It seems that WebGL content can cause videos to stutter or stop playing on that model of Macbook. I've filed a bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1035750 with a simplified test case here: https://brianpeiris.github.io/chrome-macos-webgl-video-test/

**Comment by brianpeiris** [comment] 2019-12-20 23:39
This should be partially mitigated by https://github.com/mozilla/hubs/pull/1997.

**Comment by netpro2k** [comment] 2020-04-06 22:17
Lowering to p2 since we have implemented a workaround and a fix is in progress upstream. In any case its a browser bug so not much more we can do on our end.

**Comment by brianpeiris** [comment] 2020-07-30 17:29
Looks like the chromium bug is now marked as resolved. https://bugs.chromium.org/p/chromium/issues/detail?id=1035750
We should verify, but we can probably close this now.

**Comment by takahirox** [comment] 2021-09-30 18:18
I couldn't reproduce the problem on my MacOS BigSur 11.6 + Chrome. Let's close this issue.

**Closed by takahirox** 2021-09-30 18:18 UTC
Labels: bug, P2, mac
