### ISSUE TITLE
Scene transition

### ISSUE THREAD

**Issue by broehl** [mozilla/hubs#2387] opened 2020-04-17 19:22 UTC
Right now, when a new scene is loaded for the current room, everything just goes black.

Would it be possible to have some simple (low poly) transition scene?  It would be less disorienting for newbies, who will wonder why everything suddenly went black.

**Comment by misslivirose** [comment] 2020-04-17 19:35
Thanks for the feedback! This is captured in in #2344, so I'm going to resolve it as a duplicate of that issue, But, I hadn't considered the idea of having a 3D interstitial, so I've updated that issue to link back to this one and updated it as an option to route forward. Thanks!

**Closed by misslivirose** 2020-04-17 19:35 UTC
Labels: enhancement
