### ISSUE TITLE
Black screen: ammo-debug-drawer error

### ISSUE THREAD

**Issue by modulesio** [mozilla/hubs#1048] opened 2019-03-10 05:31 UTC
Running locally on Ubuntu, black screen.

```
git clone https://github.com/mozilla/hubs.git
cd hubs
npm ci
npm start
```

Loading the page: https://localhost:8080/hub.html?hub_id=fcyg0q5

```
ammo-body.js:2 Uncaught Error: Cannot find module 'ammo-debug-drawer'
    at webpackMissingModule (ammo-body.js:2)
    at Object../node_modules/aframe-physics-system/src/components/body/ammo-body.js (ammo-body.js:2)
    at __webpack_require__ (bootstrap:78)
    at Object../node_modules/aframe-physics-system/index.js (index.js:4)
    at __webpack_require__ (bootstrap:78)
    at Module../src/hub.js (hub.js:147)
    at __webpack_require__ (bootstrap:78)
    at Object.4 (hub-0a366e822277311d0552.js:34701)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)
```

![Capture4](https://user-images.githubusercontent.com/6926057/54081061-ff44bd00-42cb-11e9-9d44-25cd5bb8ac8d.PNG)

**Comment by InfiniteLee** [comment] 2019-03-11 20:32
Hi @modulesio, we've tested on Windows, Ubuntu and Arch and cannot reproduce this issue. Did you get any errors while running `npm ci`? Perhaps try updating your npm. Also try checking out `aframe-physics-system` by itself and running that, and see if you encounter the same problem (`ammo-debug-drawer` is a dependency on `aframe-physics-system`).

**Comment by misslivirose** [comment] 2019-08-06 21:40
Given the age of this bug and being unable to repro, I'm going to close this issue but we can definitely repro if this is still occurring.

**Closed by misslivirose** 2019-08-06 21:40 UTC
