### ISSUE TITLE
Audio on standalone HMDs is choppy and often difficult to understand

### ISSUE THREAD

**Issue by jvonitter** [mozilla/hubs#1818] opened 2019-10-15 20:02 UTC
(transferring this over from https://github.com/MozillaReality/FirefoxReality/issues/1968 )

## Configuration

Firefox Reality version: 1.4.1
Firefox Reality build ID: 

Hardware: HTC Vive Focus Plus

## Steps to Reproduce

1. Enter a Hubs room with other users present and talking

## Current Behavior

The audio from the users sounds choppy/robotic.

## Expected Behavior

Smooth, clear audio.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by misslivirose** [comment] 2019-12-09 19:56
Still happening - makes being in a Hubs room unusable so bumping up priority

**Comment by misslivirose** [comment] 2020-04-20 16:24
This is being reported with other standalone headsets as well as the Vive Focus Plus.

**Comment by joshmarinacci** [comment] 2020-07-17 19:48
Is this still reproducible?

**Comment by misslivirose** [comment] 2020-07-17 23:26
Might be a duplicate of #2462, but worse on earlier hardware/versions? I think we can close this.

**Closed by misslivirose** 2020-07-17 23:26 UTC
Labels: P1, bug, has-repro
