### ISSUE TITLE
The MP4 video files are uploaded as broken links

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4895] opened 2021-12-06 16:00 UTC
**[Affected Versions]:**
- Firefox Release 94.02
- Chrome 96
- Safari v15.1

**[Affected Platforms]:**
- Windows 10x64
- macOS BigSur v11.6.1
- iOS 15.1

**[Prerequisites]:**
- Your Hubs Cloud stack is set up.
- Have a room created and opened.
- Hava an mp4 video file format available on your PC.

**[Steps to reproduce]:**
1. Click the "Place" button from the menu bar.
2. Click the "Upload" button from the menu displayed.
3. Select the MP4 video file.
4. Click the "Create Object" button and observe the behaviour.

**[Expected results]:**
- The video is correctly uploaded inside the room.

**[Actual results]:**
- The video is displayed as a broken link.

**[Notes]:**
- This issue is reproducible even when uploading the file using the chat box.
- The issue is also reproducible if the file is dragged inside the room.
- The "500 Internal Server Error" error is displayed in the browser console while reproducing the issue.
- Attached is a screen recording of the issue: 
![mp4Upload](https://user-images.githubusercontent.com/40061643/144878020-2b421057-2c29-4c0a-8578-bff652f6b935.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1186)

**Comment by keianhzo** [comment] 2022-01-06 18:57
POST media API requests have a limit of 5 mins or 150MB and from my tests this issue might be caused by big files going over that 5 mins limit and being closed. I could only reproduce this with big enough media files (not only mp4) small (1-5MB) and medium size (5-10MB) mp4s worked correctly consistently.

This is the expected behavior right now are unless this becomes a major problem for user we are not willing to raise this limits ATM.

@SV-AndreiC Could you please confirm if what I states above is consistent with this bug report?

**Comment by SV-AndreiC** [comment] 2022-01-07 08:49
@keianhzo The mp4 file used above was only 10mb and 2 mins. I have tested again with that file and also with other small, short mp4 files and I can reproduce this issue every time.
This is only occurring on the hubs cloud-beta release, hubs.com does not have this issue.

**Comment by brianpeiris** [comment] 2022-01-11 16:51
There may be an issue with the infrastructure that is causing this. I will investigate further. The root cause of this issue may also be the same root cause that led to https://github.com/mozilla/hubs/issues/4922

**Comment by brianpeiris** [comment] 2022-01-14 22:27
This turned out to be caused by an issue with our video conversion lambda. 
When we upload media, they get passed through the [Ret.Speelycaptor](https://github.com/mozilla/reticulum/blob/405fb730ec93b5284ac6dcab68ca4f94b155766d/lib/ret/speelycaptor.ex#L4) module, which operates on uploads that have a `desired_content_type` of `video/mp4`. Uploads that need to be converted then get uploaded to our [speelycaptor lambda](https://github.com/mozilla/speelycaptor) via a temporary S3 bucket. The lambda then converts the video and uploads the result to the same bucket, and returns the download URL. Ret.Speelycaptor then downloads the converted video, which it then stores. Finally the user is given the URL for the stored result.

This issue was caused by an incorrect deploy of Speelycaptor, where we accidentally released a version containing old code. The older version of the lambda did not correctly [account for the difference in S3 URLs required for the us-east-1 region](https://github.com/mozilla/speelycaptor/commit/e73f49ec791aa40c3a6611220a85b4b3dceff3c3). As a result, the video conversion was being performed, but the S3 download URL returned to Ret.Speelycaptor was incorrect. Ret.Speelycaptor would then fail to download the file, so when reticulum attempted to store the downloaded file, it would fail with a `enoent` error, which presented itself to users as a 500, since we didn't have a code-path to handle that error.

This was fixed by [deploying an up-to-date version](https://github.com/mozilla/hubs-ops/pull/143) of Speelycaptor, and adjusting the cloudformation template accordingly.

**Comment by SV-AndreiC** [comment] 2022-03-03 14:12
@brianpeiris we can't reproduce this issue anymore, is it ok to close this as fixed?

**Comment by brianpeiris** [comment] 2022-03-03 14:55
Yeah, I think we can call this closed.

**Closed by brianpeiris** 2022-03-03 14:55 UTC
Labels: bug, needs triage, [QA]:Major-issue, jira-hubs, [QA]:Regression, HC-October-Release
