### ISSUE TITLE
Phone freezes when using joysticks

### ISSUE THREAD

**Issue by gfodor** [mozilla/hubs#1388] opened 2019-06-01 03:30 UTC
On android chrome, tapping the left on screen joystick causes a frame lock and after a few seconds it unfreezes.

**Comment by johnshaughnessy** [comment] 2019-06-04 21:27
Could not repro on my pixel 2. 
Chrome 74.0.3729.157
Android 8.1.0

**Comment by gfodor** [comment] 2019-06-06 14:44
actually looks like this is coupled with being in smoke test room @johnshaughnessy

**Comment by brianpeiris** [comment] 2019-07-22 22:09
So I'm guessing this actually has to do with synchronous texture upload. Not sure if we've solved it for all texture uploads, with the preload we do now. For example, it may still be an issue for spawners in the environment?

We should at least change the title on this ticket.

**Comment by gfodor** [comment] 2019-07-22 22:42
So what is happening is the game freezes for some short interval-- my
hypothesis is that it's triggering the Android context popup for Copy/Paste
under the canvas, because I also feel a haptic vibration when it happens.

**Comment by takahirox** [comment] 2022-03-11 19:32
Let's close this issue sofar because there has been no clear way to reproduce for years. I couldn't reproduce neither. Please reopen if anyone still faces this problem.

**Closed by takahirox** 2022-03-11 19:32 UTC
Labels: needs-repro, android
