### ISSUE TITLE
Browser incompatibility error messages no longer display, breaking room entry flow on unsupported devices

### ISSUE THREAD

**Issue by Goliath3** [mozilla/hubs#2057] opened 2020-01-17 01:28 UTC
**Description**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset]
 - OS: [e.g. Windows, iOS, Linux]
 - Browser [e.g. Firefox]

**Additional context**

**Comment by johnshaughnessy** [comment] 2020-01-21 20:50
@Goliath3 We are aware that hubs does not work in Internet Explorer. This is due to certain features of web browsers we rely on not being available in Internet Explorer. For example, we use WebRTC Data Channels to communicate some of the information from one person to another, but we cannot do this in Internet Explorer: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel#Browser_compatibility  (Note: I believe this table is out of date for edge and safari on iOS and I'll submit a request for them to update it accordingly).

More information about what Data Channels are and why they are useful can be found here: 
https://www.meetecho.com/blog/data-channels-broadcasting-with-janus/

I think I may close this issue for now because we don't intend to support Internet Explorer unless it implements this feature. (I thought there may have been another feature missing, but I forget.)

For future sessions, you may try the Firefox web browser on PC, Mac, Linux, and Android. We also support Chrome on those devices. On iOS we only support Safari for similar reasons. (Apple puts restrictions on certain features that other browsers are not allowed to implement, which means we can only work properly in Safari.)

**Comment by emclaren** [comment] 2020-03-03 20:33
Hi @johnshaughnessy - it seems like there should be an error message that appears when you try to load on IE (which I think there may have been before, but it now just shows a white screen). 

This issue was recently flagged by a community member doing a post about VR platforms and Hubs browser support : https://www.linkedin.com/pulse/educators-vr-2020-international-summit-virtual-from-martins-peres/

**Comment by johnshaughnessy** [comment] 2020-03-13 18:12
Bumping the priority on this. The error message is not showing up at all - it is a blank page. (Have not tried reproducing yet)

**Comment by misslivirose** [comment] 2020-03-27 20:00
This is also causing issues in iOS - the error message doesn't display on non-Safari browsers, which results in the room entry flow breaking at the "Select Device" stage.

**Closed** 2020-06-24 19:32 UTC
Labels: P0, bug, user submitted
