### ISSUE TITLE
Non-working link with “Add to Home Screen” on iOS 

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#335] opened 2018-04-28 06:04 UTC
In Safari (iOS 11), while in a hub, using the “Add To Home Screen” function creates a shortcut that resides with other apps as expected. However, it creates an (A-frame?) icon and subsequently opening that app appears to open a webview instead of opening up an actual bookmark to that hub, which means the hub space doesn't open.

Note: using “Add To Home Screen” on the hubs.mozilla.com landing page makes a usable app button.
It would be useful to be able to make a series of app icons to easily return to previously-created/visited hub spaces.

Platform: iOS 11 / Safari / iPhone 6s

**Comment by gfodor** [comment] 2019-05-31 05:25
this is (finally) getting looked at now via https://github.com/mozilla/hubs/pull/1380. sorry it took so long :(

**Comment by misslivirose** [comment] 2019-07-22 21:29
Since 1380 was merged, @j-conrad, can you verify that this is no longer an issue?

**Comment by j-conrad** [comment] 2019-07-23 01:26
This is still not working. Just tested on Safari with iOS 12.4.
Same result as described in the original issue— app icon gets created, but only for hubs.mozilla.com, not the actual room you created. Icon is also still the A-Frame logo.

**Comment by misslivirose** [comment] 2019-07-23 18:04
Thanks for verifying!

**Comment by gfodor** [comment] 2019-07-23 18:42
Having it add a link to home screen for hubs.mozilla.com (not the room) is
intended -- that's the landing page for the PWA. By introducing the PWA
manifest for the site, it's no longer possible to create home screen links
to specific rooms. (The web manifest dictates the launch URL.) We could
support this if we wanted by serving up a room-level manifest on the room
page, but I don't think that's desirable since the concept is that you are
adding the "hubs app" to your phone.

The icon is weird. It might just be cached on your phone, but we should try
on another device to confirm.

**Comment by gfodor** [comment] 2019-07-23 18:43
BTW, the flow to save rooms is intended to be favorite the room and launch
the PWA to get the list of favorites. You could imagine this is how it'd
work if you had a "Hubs app" you installed from the app store.

**Comment by misslivirose** [comment] 2019-07-23 18:54
Great, that makes sense. So the bug (in this case) would be if the A-Frame logo is still what shows up for iOS users when they save it to the home screen, if I'm understanding correctly. The rest is by design with the favorites feature and manifest.

**Comment by gfodor** [comment] 2019-07-23 23:00
Yup. and we should confirm that A-Frame icon on another device. I'm pretty
sure I tested it and the manifest is correct, so it might just be a cache
on Jim's phone from the last time he installed it.

**Comment by j-conrad** [comment] 2019-07-24 02:09
Ok then. The A-frame icon only shows up if I attempt to do ‘Add to Home Screen’ with a Hubs room. It does not occur if I do it with the main landing page. Although it’d be cool if it used some logo other than a blank white rounded square. Looks like it attempts to grab a screenshot of the page or something.

**Comment by gfodor** [comment] 2019-07-24 02:33
Ah not sure about that one either. Sounds like iOS does something weird
with PWA icons, I must have overlooked it. Thanks for checking.

**Comment by cvan** [comment] 2019-07-24 07:00
hiya, folks! opened PR #1557 to address.

- Apple shipped support in [Safari for iOS 11.1](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW6) for parsing [web-app manifests](https://w3c.github.io/manifest/) via `<link rel="manifest">` but (for some reason) ignores the `icons` defined in the manifest. A `<meta name="apple-touch-icon">` tag appears to be still required for the time being. (I assume that'll change in an upcoming release.)
- Having the Hubs scene page define its own `<meta name="apple-touch-icon">` will fix the issue of A-Frame's injecting its own (which it does if it's missing, along with [a few other Apple-proprietary `<meta>` tags](https://github.com/aframevr/aframe/blob/c871d04e/src/core/scene/metaTags.js#L14-L16).

**Comment by joshmarinacci** [comment] 2020-07-17 20:05
I think this is fixed now, yes?

**Comment by misslivirose** [comment] 2020-07-17 23:09
Confirming that the A-Frame logo no longer appears for a Hubs room. It's now the duck logo :)

**Closed by misslivirose** 2020-07-17 23:09 UTC
Labels: enhancement
