### ISSUE TITLE
After loading some kind of assets on a custom glb scene it freezes

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [mozilla/hubs#539] opened 2018-08-31 15:14 UTC
[untitled.zip](https://github.com/mozilla/hubs/files/2340611/untitled.zip)

I've tried this on

Chrome: 68.0.3440.106 (Official Build) (64 bit)
Nightly: 63.0a1 (2018-08-31) (64-bit)

If you try to load certain assets on a cutsom glb scene the scene and interaction freezes completely (after it actually loads), you can still listen and talk to other people, but can't move and can't see their updated location, also the "invite others" still appears if everybody leaves.

These are the tests I've made

**Assets that freeze the scene**

- Link to images or gifs
- GLB models both online and dropped

**Assets that can be loaded**

- PDF both online and dropped
- Dropped images
- Youtube Videos
- Dropped Videos

There are no errors shown on the console when this happens...

I've attatched the zip with the glb I'm loading

**Comment by brianpeiris** [comment] 2019-01-01 02:33
I'm not able to reproduce the issue with the attached GLB. Please let us know if you're still running into this problem.

**Comment by gfodor** [comment] 2019-02-28 01:33
Closing for now, feel free to re-open if persists

**Closed by gfodor** 2019-02-28 01:33 UTC
Labels: bug, user submitted
