### ISSUE TITLE
iOS Safari: Home Screen link gives ‘unsupported browser’ message

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#1702] opened 2019-08-24 20:18 UTC
![60F49A9B-8A47-44AA-ADDF-E00DC7FA3ECE](https://user-images.githubusercontent.com/31968496/63646243-441aaf80-c6c4-11e9-8e97-fd1ed79bdc41.png)
**Description**
Open Hubs in Safari works fine, but that same page saved with ‘Add to home screen’ returns the ‘unsupported browser’ pop up when clicking on ‘Create a Room’.

**To Reproduce**
1. In Safari (iPhone), go to Hubs homepage
2. Click on the ‘send’ button and choose ‘Add to Home Screen’
3. Exit Safari
4. Click on the newly created app icon
5. Try to ‘Create a Room’
6. Result: pop up about unsupported browser

**Expected behavior**
Room should be created

**Screenshots**
![046C301F-C8C6-488F-944A-636D3C5073EC](https://user-images.githubusercontent.com/31968496/63642270-97afdd80-c671-11e9-885f-4553d0eed5db.png)

**Hardware** 
 - Device: iPhone 6s
 - OS: iOS 12.4
 - Browser: Safari

**Additional context**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-240)

**Comment by gfodor** [comment] 2019-08-24 22:25
Yup pretty sure we can’t yet support add to home screen  since WebRTC doesn’t work

**Comment by j-conrad** [comment] 2019-08-25 00:32
Curious what changed? The app icon I had on my home screen worked for a really long time until recently.

**Comment by gfodor** [comment] 2019-08-25 05:15
Oh, it did? Maybe I'm wrong about this then.

**Comment by j-conrad** [comment] 2019-08-25 06:06
Here’s something that appears to be different from when it worked: 
When opening from the Home Screen app icon, it doesn’t actually open Safari like it used to. In other words, it used to open a new tab within Safari. Now, it appears as it’s own (unknown) app. I’ll try to add a screenshot from my phone.... maybe in the original issue above.

**Comment by joshmarinacci** [comment] 2020-07-17 19:56
Can this still be reproduced?

**Comment by takahirox** [comment] 2021-09-30 18:31
I couldn't reproduce the problem on my iPhoneX iOS 15 + Safari. Let's close this issue. Please reopen if you still face the problem.

**Closed by takahirox** 2021-09-30 18:31 UTC
Labels: bug, P2, ios, jira-hubs, safari
