### ISSUE TITLE
Touching objects on iOS sends them flying

### ISSUE THREAD

**Issue by OddHouseGames** [mozilla/hubs#2360] opened 2020-04-10 01:48 UTC
Touching/placing objects in iOS safari browser sends them flying.

**Comment by joshmarinacci** [comment] 2020-07-17 17:55
Could you give us more information about what exactly is happening?

**Comment by misslivirose** [comment] 2021-01-06 18:17
Closing issue - we can re-file a new bug if this behavior occurs but we have not gotten a clear repro of the issue.

**Closed by misslivirose** 2021-01-06 18:17 UTC

**Comment by misslivirose** [comment] 2021-01-06 18:18
(Likely dupe of #2348)
