### ISSUE TITLE
Saying "Yes" to "Allow VR Device access" on mac firefox causes LONG delay

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#2240] opened 2020-03-18 13:18 UTC
**Description**
If I go to a Hubs room on Firefox on MacOSX and say "yes" to the WebVR perm prompt, it hangs for a good long time.

**Expected behavior**
It shouldn't hang.  

**Hardware** 
 - Device: Desktop iMac
 - OS: latest macosx 
 - Browser latest Firefox

**Comment by johnshaughnessy** [comment] 2020-03-18 22:08
One part of the problem is that in hubs we are waiting for `getVRDisplays` to resolve before continuing page load. We will fix that part on our own. 

As for the long stall, this needs to be fixed in Firefox. @blairmacintyre  Any details you can provide in this bug report may  help Kip / Daosheng / others diagnose the problem and fix it: https://bugzilla.mozilla.org/show_bug.cgi?id=1623487

**Closed** 2020-04-07 21:44 UTC
Labels: bug, needs triage
