### ISSUE TITLE
unlike Chrome, Samsung Internet does not offer Enter on Phone

### ISSUE THREAD

**Issue by machenmusik** [mozilla/hubs#2413] opened 2020-04-23 19:47 UTC
**Description**
unlike Chrome, Samsung Internet does not offer Enter on Phone.
only a weird single-eye-view broken VR of version is presented.

**To Reproduce**
Use Hubs on Android phone with Samsung Internet browser.

**Expected behavior**
Like Chrome, expected to see Enter on Phone as an option

**Screenshots**
NA

**Hardware** 
 - Device: Android, especially Samsung phones with Samsung Internet as default
 - OS: Android
 - Browser: Samsung Internet

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-375)

**Comment by johnshaughnessy** [comment] 2020-04-30 07:57
Marked as P1 (high priority) because many phones may have this browser as a default. Need to test to see if Hubs will work in this browser and, if so, make sure we are presenting the correct app view / controls.

**Comment by matthewbcool** [comment] 2021-10-06 01:34
I was unable to reproduce on samsung galaxy 8 with sumsung internet. Touching "Enter on Device" and then "Enter in VR" works as expected.

**Closed by matthewbcool** 2021-10-06 01:34 UTC
Labels: bug, P1, jira-hubs, android

**Comment by Softvision-GeluHaiduc** [comment] 2021-10-06 09:51
I can also confirm that this issue is no longer reproducible.
