### ISSUE TITLE
Lightmaps failing to load for simple project

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#3324] opened 2020-11-12 16:07 UTC
[This zip file](https://github.com/mozilla/hubs/files/5531730/lightmap-test.zip) contains a Blender project and the subsequent GLTF export. If you import the GLTF file into Spoke you can see the lightmap output:

<img width="1055" alt="Screenshot 2020-11-12 at 16 03 03" src="https://user-images.githubusercontent.com/303516/98964382-a4338680-2500-11eb-9f84-8c0b70fedb8e.png">

...but if you publish and view the scene in Hubs the lightmap isn't shown...

<img width="773" alt="Screenshot 2020-11-12 at 16 03 35" src="https://user-images.githubusercontent.com/303516/98964477-bf05fb00-2500-11eb-943e-f9d9a35804ec.png">

Dropping the lightmap resolution in Blender from 2048x2048 to 512x512 fixes the problem. This implies a memory issue, but that texture loads just fine if you attach it to something else. I wonder if it's a race condition and the lower sized textures just load faster.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-468)

**Comment by j-conrad** [comment] 2020-11-12 18:50
I think I may have found out what's going on, although I'm not 100% sure why.

I noticed in your .blend file, you have the the glTF/glb export options saved (which helped diagnose this one). Under the **Geometry** section, the option for '**Normals**' was unchecked. 
![image](https://user-images.githubusercontent.com/31968496/98982448-46894500-24d4-11eb-85ab-6b122925fbcc.png)

This is normally (ha!) checked by default. I'm not sure exactly how this flag interacts with lightmaps, but when I exported a version of the .glb with this flag ON, the object displays its Lightmap correctly in both Spoke and Hubs.

I did, however, see the same issue where your original .glb shows just fine in Spoke, but then does NOT in Hubs. I'm curious about the discrepancy, but an engineer could probably answer this part.

In this screenshot, the one with the lightmap showing had its 'Normal' checkbox turned ON before export where the other one did not.

![image](https://user-images.githubusercontent.com/31968496/98982358-235e9580-24d4-11eb-9b1d-823ab0ce0067.png)

Side note:
There is a lot of wasted space on both of those textures (baseColor and lightmap), but I'm assuming there might be other parts of a model on it. If not, you could get away with having a much smaller texture (almost 75% smaller) by spreading those UVs out over the whole UV space. But regardless, it does NOT appear to be a texture size / memory issue.

**Comment by j-conrad** [comment] 2020-11-12 19:01
I'd like to keep this issue OPEN until we can understand why there's a difference between how the 'broken' object displays in Spoke vs. Hubs.
@netpro2k   @robertlong

**Comment by rawnsley** [comment] 2020-11-13 11:28
@j-conrad I can confirm exporting with normals works for me as well! I wonder if it also changes the load times enough to prevent the race condition (wild speculation). Actually I'm not so sure about the race condition theory as it's consistently broken across computers and browsers.

Yes, this is part of a larger scene where the whole of the texture bitmaps are used - this is just the minimum reproduce I could find.

Exporting with normals moves me forward at least, but I would rather not in general as this is an unlit scene and the normals aren't otherwise required.

**Comment by BonzoMartini** [comment] 2020-11-15 14:59
I too have this issue however I also get a gltf validation error "unsupported extension"
is there a tutorial about an official method to get models from Blender to Hubs?

**Comment by rawnsley** [comment] 2020-11-15 15:06
@BonzoMartini [This video](https://www.youtube.com/watch?v=ldHwbnMMKVY) covers it very well.

**Comment by BonzoMartini** [comment] 2020-11-15 15:11
@rawnsley Yes that's what I followed originally

**Comment by rawnsley** [comment] 2020-11-15 15:17
@BonzoMartini Depending on where you get it, I think you can ignore that error message: technically it is just saying that the _MOZ_lightmap_ extension is unsupported in whatever tool you are viewing it in, which is not surprising as only Hubs supports it.

**Comment by BonzoMartini** [comment] 2020-11-15 16:10
ok thanks, goot to know. I don't get any lightmap in Hubs, however, only in Spoke

**Comment by rawnsley** [comment] 2020-11-15 17:07
Yup, that's the same problem I'm getting. Try jconrad's trick of exporting the normals just in case it works

**Comment by BonzoMartini** [comment] 2020-11-15 19:39
ok I exhaustively followed the tutorial vid (again) and if you follow exactly lightmaps work and show in Hubs. 
(However the floorplan collision is off by 4 meters in 1 direction)

**Comment by rawnsley** [comment] 2020-11-15 19:41
Somebody else had that problem recently. Try deleting the floor plan node and readding it. You're not having much luck!

**Comment by BonzoMartini** [comment] 2020-11-15 19:43
> Somebody else had that problem recently. Try deleting the floor plan node and readding it. You're not having much luck!

Yep that did it

**Comment by LAGENCECREE** [comment] 2020-11-17 18:34
@rawnsley  followeds methods of tutorials*, still ONLY work on spoke AND NOT on hub :/

(* At object level, Texture on primary "UVMap" > background component > Material output + lightmap on secondary "LightmapUV" > MOZ_lightmap + Hub component checked at glb export ).

_Tested with Blender 2.90.1 + hubs blender exporter 0.0.4 + import/export gltf 2.0 v.1.3.48_

**Comment by BonzoMartini** [comment] 2020-11-17 20:44
I got my lightmaps to work consistently after following the tutorial from the video above and literally making the exact same thing they do. Then magically lightmaps in other blender projects began to work. 
BUT 
I also rebooted PC and reloaded the Spoke. 
Sometimes now if I iterate with a blender project, the material doesn't come out in Spoke. Have to restart blender when that happens. Also incrementing the name of the exported glft file and lightmap textures instead of overwriting the same file.

**Comment by j-conrad** [comment] 2020-11-17 22:02
You may find it helpful to first test your exported object(s) in a generic glTF viewer like these:

- https://gltf-viewer.donmccurdy.com/
- https://playcanvas.com/viewer

That way, you can diagnose what's specific to Spoke/Hubs vs. your file.
It's important to note, however, that most viewers will not display Hubs-specific components (like the lightmap) or any other glTF extensions you may be using.

**Comment by LAGENCECREE** [comment] 2020-11-18 13:46
thankx for info guys.

@j-conrad , in fact [glb doesnt not support lightmap natively](https://github.com/n5ro/aframe-extras/issues/279), the given viewers support hubs components ? in my case lightmap is not displayed 
@BonzoMartini my lightmapped model work on spoke but not on hub, i 'm afraid that is not exactly the same 3D engine integration in both platforms,  so i guess my blender export is fine. but will try a reboot.

i will investiguate low level regarding this @robertlong push
https://gist.github.com/robertlong/d9042bb1d7c28270693cb7232c768046

but hope material editing in a future can be done on a friendly way on SPOKE and lightmapping applied to simplified for real time PBR material too

**Comment by brianpeiris** [comment] 2021-06-15 18:47
It's unclear to me how critical this issue is. I assume we do want to encourage creators to use lightmaps where possible, so perhaps this should be P1. Though it did seem like enabling normals on export was a work around? 
Feel free to bump the priority on this one if necessary.

**Comment by brianpeiris** [comment] 2021-06-15 18:53
Oh, actually, I just tried to reproduce the issue and I couldn't. Both test GLB files linked above now work correctly in Hubs. I assume we managed to fix this in an update since November. Unless there's reason to keep this open, I think we can close this issue.

**Closed** 2022-03-03 21:16 UTC
Labels: bug, P2, jira-hubs
