### ISSUE TITLE
Favourites remain when their room is closed

### ISSUE THREAD

**Issue by broehl** [mozilla/hubs#2270] opened 2020-03-23 02:41 UTC
How to replicate:

Create a room
Mark is as a favourite
Close the room

The room is still in your favourites list, but no longer exists. There's no way to remove it from your favourites list.

**Comment by kwadroke** [comment] 2020-03-23 04:34
Duplicate of #2148

**Comment by misslivirose** [comment] 2020-03-23 14:17
Thanks for filing! I'm going to resolve since it's a dupe, but we appreciate the filing, @broehl!

**Closed by misslivirose** 2020-03-23 14:17 UTC
Labels: bug, needs triage
