### ISSUE TITLE
[UX Enhancement] Room Details Scrollbar

### ISSUE THREAD

**Issue by flowpoly** [mozilla/hubs#1484] opened 2019-06-26 11:55 UTC
As a user, when I view my room's details, there's a scrollbar that shouldn't be there.

![Scrollbar](https://user-images.githubusercontent.com/38146102/60177761-bb78b380-97e7-11e9-9a58-8a1162cb2400.jpg)

**Comment by misslivirose** [comment] 2019-07-08 17:52
Expected behavior: In the case where the attributions list of a scene is short, do not show an inactive scrollbar, but instead hide it until the attribution list is long enough to require one.

The Moz Atrium Scene (https://hubs.mozilla.com/scenes/GJiBCbG/moz-atrium) has a lot of model attributions and would be a good scene to test with a longer list.

**Comment by Shivansh2407** [comment] 2019-10-07 01:21
Can you please tell how to contribute to this issue?

**Comment by misslivirose** [comment] 2019-10-07 15:52
Hi @Shivansh2407! If you'd like to work on this, I can assign it to you and you can read through the [contributing guidelines](https://github.com/mozilla/hubs/blob/master/CONTRIBUTING.md) if you haven't already taken a look there. We can answer questions here or in the Discord server.

**Comment by SparshKat** [comment] 2020-01-03 11:36
I would've loved to work on this but i can't see any scrollbar on clicking room info button. If this issue has been solved then kindly close it :) @misslivirose @flowpoly 
![Screenshot 2020-01-03 at 4 59 35 PM](https://user-images.githubusercontent.com/32457916/71721480-397ade80-2e4b-11ea-9dce-8fa584c35b2f.png)

**Comment by brianpeiris** [comment] 2020-01-03 19:25
I believe the scrollbar only appears on Windows, since Macs usually have invisible scrollbars to begin with.

**Comment by SparshKat** [comment] 2020-02-09 12:36
I think changing the CSS of the parameter from 'overflow-y : "scroll" ' to 'overflow-y : "auto " ' should do the work! I'd make the changes and push the PR if you want me to :)

**Closed** 2020-10-12 17:38 UTC
Labels: enhancement, good first issue, paper cuts
