### ISSUE TITLE
Spawned text messages are cut off at the bottom

### ISSUE THREAD

**Issue by markusTraber** [mozilla/hubs#5710] opened 2022-09-12 14:59 UTC
**Description**
When you spawn a chat message via the magic wand, the text of the last line is cut off slightly, see screenshot.

**To Reproduce**
1. Go to into a Hubs room.
2. Open the chat.
3. Write a test message.
4. Click onto the magic wand icon.
5. See the cut off text message in the room, similar to the attached screenshot.

**Expected behavior**
The text should not be cut off at the buttom.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12909076/189686464-c8f3ded0-c76b-408c-8ec9-b298c4f36b2e.png)

**Hardware** 
 - Device: Desktop, Macbook Pro 16 M1Max
 - OS: MacOs
 - Browser: Firefox 104.0.2

**Additional context**
Noticed it first when applying the Hubs Cloud September Update to my custom client, but also affects the Mozilla Hubs Instance.

**Comment by matthewbcool** [comment] 2022-09-14 00:30
Thank you for documenting this one. Confirmed in Chrome as well.

**Comment by lavender-snow** [comment] 2022-09-14 10:16
I have not reached the root cause of the problem, but have confirmed that this problem occurs when using `html2canvas` version `1.1.0` or later.

**Comment by matthewbcool** [comment] 2022-09-23 17:54
Duplicate of https://github.com/mozilla/hubs/issues/5710

**Closed by matthewbcool** 2022-09-23 17:54 UTC
Labels: bug, needs triage
