### ISSUE TITLE
constant "Unable to connect to this room" crashes on firefox while Chromium works well

### ISSUE THREAD

**Issue by antonkulaga** [mozilla/hubs#5328] opened 2022-04-03 21:19 UTC
We tested Mozilla hubs yesterday ( the room was https://hubs.mozilla.com/oRsGY58/antons-room?default_material_quality=high&default_mobile_material_quality=high&filter=featured&media_nav=false&selectAction=use ) and two out of three firefox users had huge issues and had eventually switch to Chromium to make it work. In particular, they complained about:
```
Unable to connect to this room, please try again later.  You can try connecting via TCP, which may work better on some networks.
```
This was after some messages about constructing objects (along with pretty icons visible for an instant each). Clicking on the TCP part, which was a link, did not change anything. They used the latest firefox and after seeing first bugs they switched off extensions to make sure it is not extensions that cause trouble. There were also multiple troubles with the camera and microphone which again worked much better in other browsers.

It is really an irony, that Mozilla's product works well in any browser other than its own Firefox!

**Comment by Levithan7** [comment] 2022-04-25 01:38
That's really interesting. I had the exact same error but it only appeard in chrome and worked perfectly fine in FireFox. I have a few questions:

1. Could you solve the problem? (beside using Chrome instead of Firefox) 
2. Could you may provide your Chrome and FireFox Versions used? 
3. Could you may tell me where you tried to connect from? I had problems with 3 different people, all from germany
4. Did you / they use Hubs on Desktop or on Phone?

Have a good day!

**Comment by cornelionce** [comment] 2022-05-02 12:47
This seems to be the same behavior described in https://github.com/mozilla/hubs/issues/5380.
I think we can close this issue and track it there since we have more details and it would be easier to gather all the information in one place.

@antonkulaga -- if this still reproduces on your side, please provide additional details in https://github.com/mozilla/hubs/issues/5380. Did you, by any chance, ran into this issue by being in Germany or using a vpn?

**Closed by cornelionce** 2022-05-02 12:47 UTC
Labels: bug, needs triage
