### ISSUE TITLE
"you are now signed in" modal does not close.

### ISSUE THREAD

**Issue by amychurchwell** [mozilla/hubs#2119] opened 2020-02-10 19:19 UTC
**Description**
"you are now signed in" modal after signing up for an account does not close.

**To Reproduce**

Not logged in. No existing account.

1. Navigate to 'https://hubs.mozilla.com/1rNht23/hubs-commons/'
2. Click 'enter room'
3. Click 'browse avatars'
4. Click 'create avatar'
5. Enter email in dialog.
6. Click sign-in link in email.
7. See "you are now signed in" modal and attempt to close. Both "close" button and upper left `x` button do not work.

**Expected behavior**
"close" button and upper left `x` button should close modal.

**Screenshots**
![Screen Shot 2020-02-10 at 9 56 57 AM](https://user-images.githubusercontent.com/30483988/74178085-d15cac80-4bef-11ea-88d8-7ee96d35eef8.png)

**Hardware** 
 - Device: desktop
 - OS: macOS Catalina
 - Browser: Firefox Developer Edition 73

**Additional context**
No existing account before entering email.

**Comment by gfodor** [comment] 2020-02-10 19:22
Thanks for the report! I'm unable to reproduce this on windows in chrome or firefox. Might be mac-specific.

**Comment by johnshaughnessy** [comment] 2020-02-10 22:16
Unable to repro on linux. Need to try on a mac

**Comment by joshmarinacci** [comment] 2020-07-17 19:26
This was never reproduced so I'm going to close it.

**Closed by joshmarinacci** 2020-07-17 19:26 UTC
Labels: P2, bug
