### ISSUE TITLE
When Room is embedded on my website room gets stuck on the choose device screen

### ISSUE THREAD

**Issue by Goliath3** [mozilla/hubs#2055] opened 2020-01-17 01:07 UTC
I embedded a Mozilla Hub Room on my website and when trying to load the room the room got stuck on the choose input screen. I tried several times and kept having the same problem.

**Comment by gfodor** [comment] 2020-01-17 01:12
Hey there, would you mind sharing a link to the room? You can DM me on our discord or email me at gfodor@mozilla.com if it's private.

**Comment by misslivirose** [comment] 2020-03-23 14:41
I'm going to resolve this as a dupe of #2238 - multiple reports of this and I'm wondering if it's related to the issues with devices in general (e.g. what we see in #2240)

**Closed by misslivirose** 2020-03-23 14:41 UTC
