### ISSUE TITLE
[macOS] The shared camera and screen are not visible or they are not spawned at all

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4675] opened 2021-09-27 13:56 UTC
**[Affected Versions]:**
- Safari 15

**[Affected Platforms]:**
- macOS Big Sur 11.6

**[Prerequisites]:**
- A room is created and opened on https://hubs.mozilla.com/.

**[Steps to reproduce]:**
1. Click  on the "Share" button.
2. Select one of the options from the menu displayed.
3. Allow permissions from the device prompt if displayed.
4. Observe the behavior.

**[Expected results]:**
- The camera/screen are spawned into the room.

**[Actual results]:**
- The camera/screen are not spawned.
OR
- A black view of the spawned camera/screen is displayed.

**[Notes]:**
- If I click the create button, the image is correctly taken, displaying the correct view.
- Attached are a screen recordings of the issue: 
	- Loading state: [link](https://drive.google.com/file/d/1TDSqi_ikzreolPzaiI4bCILEAYevlw6f/view?usp=sharing).
	- Black view: [link](https://drive.google.com/file/d/1xD3b8tChxiNMPzqSu6bky5mwZ5tzWpIN/view?usp=sharing).
	- Console Logs: [link](https://drive.google.com/file/d/1gEo6STu7iSTkm0UEgR7juT-VXpJ9Y7-v/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-918)

**Comment by takahirox** [comment] 2021-09-28 19:30
I can reproduce black view problem but couldn't reproduce non-spawned problem so far.

Regarding the black view problem, it sounds like failing to render video user media (web cam streaming). Videos are rendered, so maybe video user media specific problem.

**Comment by takahirox** [comment] 2021-09-28 20:18
I confirmed I can't reproduce the problem on iPhoneX (iOS) so the problem seems to be MacOS specific.

**Comment by keianhzo** [comment] 2022-05-10 12:25
@SV-AndreiC Is this still happening? I can't reproduce it anymore in MacOS Safari 15.4

**Comment by SV-AndreiC** [comment] 2022-05-11 09:55
@keianhzo I have tested this on MacOS Safari 15.4 and could not reproduce the behavior anymore. The shared camera and screen are successfully spawned.

**Comment by takahirox** [comment] 2022-05-13 21:41
OK, so let's close this issue. Please reopen if anyone still encounters the problem.

**Closed by takahirox** 2022-05-13 21:41 UTC
Labels: bug, P2, needs triage, mac, [QA]:Major-issue, [QA]:Verified-fixed, WIP, jira-hubs, safari
