### ISSUE TITLE
Reloading Mozilla Hubs page caused 20GB of memory allocation

### ISSUE THREAD

**Issue by nbp** [mozilla/hubs#2587] opened 2020-06-25 15:50 UTC
**Description**

`console.error` create huge memory consumption and slow down. The problem is likely the number of recursive calls of `{Object,Array,Value}ToSource` functions made by `console.error`.

Maybe the error logging should not attempt to log large structures, and fallback on a limited set of dump-ed elements.

Profile: https://share.firefox.dev/37ApmNx
See https://bugzilla.mozilla.org/show_bug.cgi?id=1646046
CC @whimboo

**Comment by misslivirose** [comment] 2020-10-12 22:48
I noticed in the bugzilla ticket that this happened on virtu-allhands - does this also happen on hubs.mozilla.com?

**Comment by brianpeiris** [comment] 2021-01-23 01:24
Left a comment on the bugzilla ticket. As I understand it, there are cases where we spam call console.error that causes this memory leak. I was able to reproduce this artificially by adding the following line to a `tick` method (for example, in idle-detector.js). The "test" string is important here, since it forces the console to stringify the error object, which results in `toSource` begin called, as mentioned in the issue description. 
This causes firefox to stall initially, then eventually you lose the connection to the room, and then the memory leak takes off, consuming many hundreds of megabytes in a matter of seconds. Note that this memory leak only occurs if your dev tools are open, spamming console.error logs does not cause an issue in normal use.

```js
console.error("test", new Error("an error"));
```

We definitely use this pattern in many parts of our code, where we log an error to the console with a message and the original error object. It's hard to say which of these instances actually result in console.error being spammed repeatedly, and in what situations that occurs.

Given this only happens in scenarios where the client has broken in some way, and something causes console.error spam, and you have your dev tools open, I'd lean towards labeling this a low priority issue, or perhaps even closing it entirely, since we haven't had repeated reports of it. If anything, this is something we should be on the watch for as a team, so that we can identify the scenarios where this happens, and target a fix for it.

**Comment by brianpeiris** [comment] 2021-01-26 20:43
I've submitted a reduced test case as a bug against devtools, since I think the browser ought to handle this error logging scenario in a better way https://bugzilla.mozilla.org/show_bug.cgi?id=1688971

**Closed** 2021-02-23 19:59 UTC
Labels: P3, bug, needs-repro
