### ISSUE TITLE
Add a nudge about how to mute users in unmoderated rooms

### ISSUE THREAD

**Issue by emclaren** [mozilla/hubs#1935] opened 2019-11-26 18:53 UTC
**Is your feature request related to a problem? Please describe.**
I attended an event with no moderator in Hubs. A couple attendees were being loud and in others' space. Had the moderator been in the room they may have been removed. After I shared how to mute folks in the text-chat, a number of people mentioned that being able to control others volume improved their experience, and they wouldn't have known to do this since it was their first time in Hubs.

**Describe the solution you'd like**
When entering a room with no moderator present, it would be nice if there was a nudge or pop-up about how to mute other users.

**Comment by gfodor** [comment] 2019-11-26 19:52
I'd be curious if the main gate here is just learning how to open the
menus. On 2D particular, that feature is (by design) un-intuitive since
we've focused on making it a hardware button you must be taught by the
system. The only mechanic for teaching that right now is the tip UX.

Beyond the tip UX, it's hard to say if we should expand into further
callouts for user education. It could quickly become too noisy. I'd support
us adding a specific mechanic beyond tips though that very firmly forced
the user to discover the menus, since it's such a crucial thing.

**Comment by emclaren** [comment] 2019-11-27 19:05
Building on this issue - I received community feedback that even in moderated rooms, users don't known how to open the menus to open the volume in 2D mode. 

Should I close this enhancement request and open a new one about improving discoverability of 2D menus?

**Comment by misslivirose** [comment] 2019-12-02 16:08
Could we find screen real estate to put this in the lobby flow somewhere? I'm thinking we could put a small alert badge and message on the room attendee list if there is no present room owner. Maybe this has a link to controls / gif that explains how to interact with users.

I think that needing to improve our other mechanics for teaching various components of the system is probably valid, but a larger project discussion that we should do aided by usability research.

**Comment by misslivirose** [comment] 2020-03-31 22:41
Going to close this as an additional consideration as part of the overall tutorial / instructional flow

**Closed by misslivirose** 2020-03-31 22:41 UTC
Labels: enhancement
