### ISSUE TITLE
Right click to zoom only works the first time in a room

### ISSUE THREAD

**Issue by larsbergstrom** [mozilla/hubs#2426] opened 2020-04-27 17:27 UTC
**Description**
If I right-click to maximize an image or slide in a slide deck, it works the first time and sticks. Then if I hit ESC to exit and right-click anything else to focus, the object just toggles focused/defocused unless I hold the right button the whole time.

**To Reproduce**
1. Go to a room with an image
2. Right-click on the image to see focused
3. Press ESC to get out of the focus
4. Right-click the image again

**Expected behavior**
Second time that I use right-click, the object still maximizes.

**Actual behavior**
The image maximizes, but then de-maximizes immediately.

**Hardware** 
 - Device: Desktop
 - OS: Mac
 - Browser: Firefox Developer Edition

**Comment by johnshaughnessy** [comment] 2020-04-30 06:36
Duplicate of https://github.com/mozilla/hubs/issues/2192 

Surprisingly, the bug is that it worked that way the first time, because the feature was designed such that you _have_ to hold the right mouse button. 

That being said, we may want to change the design so that right click is a toggle like you thought it would be. I think I'd prefer that instead of having to hold a button down. There are also some tie-ins with the object info modal and object menus that we should consider.

**Comment by gfodor** [comment] 2020-04-30 14:14
hard to say if this should be a modal. the goal of this feature is to be able to quickly "peek" at objects when they are hard to see/read. i do this often for text labels, images at a distance, etc, usually for a second or two. if we wanted a way to actually bring up the full object modal experience from an on-object action, that seems fine, but i'd hate to see us abandon the current mechanic.

**Comment by gfodor** [comment] 2020-04-30 14:17
two approaches:

- Add a modifier key, so shift left or shift right click goes to object list UX
- If you press and hold for more than N seconds, it sticks

The latter is a bit magical, but would be more discoverable if we had an on-screen "fill circle" like is often used with gaze interactions in VR indicating something will happen if you hold it down for a while.

**Comment by Charlesc22** [comment] 2020-04-30 18:27
I can give an example of where it would be important for it to toggle or lock somehow.

If somebody is giving a presentation using a slide deck, you would want to right-click it and have it stay zoomed so you could follow the presentation.
Probably the same if a video was running and you would watch the video in full screen without laughing a separate tab.

**Comment by misslivirose** [comment] 2020-05-06 21:59
@johnshaughnessy - since this is a dupe of #2192, which you filed, can you comment on which of these issues we should keep open to track and which one we should resolve?

**Comment by misslivirose** [comment] 2020-06-29 20:34
Resolving as dupe of #2192

**Closed by misslivirose** 2020-06-29 20:34 UTC
Labels: P2, bug
