### ISSUE TITLE
Customize Sign-in email to prevent spamfilters and improve user experience

### ISSUE THREAD

**Issue by camelgod** [mozilla/hubs#3181] opened 2020-10-15 20:24 UTC
**Is your feature request related to a problem? Please describe.**
The sign-in link email content is not often very descriptive depending on the Hubs-cloud situation. It also often ends up in junk / spam folder.
To reduce likeliness of hitting spam-filters, I would like to add more information such as contact information / report abuse etc.

I would also like to give a more bespoke welcome message and additional information.

**Describe the solution you'd like**
A textarea field in admin panel server settings where you can customize the email content using a variable such as [[ invite_url ]] for the link.

**Describe alternatives you've considered**
There is no way for me to edit the reticulum server.
Alternatively:
Not customizeable but injecting company name + contact email / or a section for contact information based on variables from admin panel into the email.

**Additional context**
Saw this discussed here but couldnt find anything in search feel free to merge if you find that.
https://github.com/mozilla/hubs/discussions/2734

**Comment by misslivirose** [comment] 2020-10-15 20:42
This is documented in https://github.com/mozilla/hubs-cloud/issues/111 and is being implemented in #3151 . Going to resolve this as a duplicate of those.

**Closed by misslivirose** 2020-10-15 20:42 UTC
Labels: enhancement
