### ISSUE TITLE
A-frame text is not displaying in iOS

### ISSUE THREAD

**Issue by Sawher1999** [mozilla/hubs#5183] opened 2022-02-24 11:58 UTC
**Description**
text in tag <a-entity> doesn't show in iOS platfrom. I know the problem is with the version of dependencies but I don't know which one. 

**To Reproduce**
1. Go to 'hub scene'
2. press and hold 
3. See error

**Screenshots**
![S__12050447](https://user-images.githubusercontent.com/89853664/155519662-11d22a0f-b65b-4ce3-a3d8-c3677b47c233.jpg)

**Hardware**
 - Device: [iphone and ipad]
 - OS: [ iOS ]
 - Browser: [Safari, Chrome and Firefox]

**Comment by takahirox** [comment] 2022-03-11 20:28
Hi, thanks for the problem report.

Unfortunately I couldn't reproduce it on my iPhoneX iOS 15.3.1 Chrome. Could you share more details with us?

1. What iOS/iPad models do you use?
2. What are iOS/iPadOS versions?
3. What scene did you encounter the problem? Can you share the scene with us?

**Comment by brianpeiris** [comment] 2022-04-08 20:03
I could not repro this on my iPhone 11 either, using Safari 15.4. It might have been a bug we fixed after the troika text update. I'm inclined to close this bug for now unless the reporter, or someone, can still reproduce the issue.

**Comment by cornelionce** [comment] 2022-04-29 06:35
I'm also unable to reproduce this using an iPhone 12 mini and an iPhone 13, both running iOS 15.4.1.
Closing the issue since there was no reply for the past 20 days and we are lacking additional information.

@Sawher1999 if this issue still happens on your side please share more details and we will reopen the ticket.

**Closed by cornelionce** 2022-04-29 06:35 UTC
Labels: bug, P1, P2, needs triage, needs-repro, ios
