### ISSUE TITLE
Room links and room codes don’t work on my network

### ISSUE THREAD

**Issue by SV-AndreiC** [mozilla/hubs#4876] opened 2021-11-29 17:03 UTC
**[Affected Versions]:**
- Firefox Release 94.02
- Chrome 96.0.4664.45

**[Affected Platforms]:**
- Windows 10x64
- iOS 15.1

**[Prerequisites]:**
- Have a room created and opened.
- Have “Shared Link” enabled in “Room Settings”
- Have access to another user account.

**[Steps to reproduce]:**
1. Click the “Invite” button.
2. Send the room link or the room code to a different user.
3. Use the room link or room code with the other user to join the room.

**[Expected results]:**
- The second user joins the room.

**[Actual results]:**
- When using the link the user receives a forbidden page.
- When using the code the user receives the “We couldn’t find that code. Please try again”.

**[Notes]:**
- If I switch the room access to “Invite only” in Room Settings, that link works fine.
- This only seems to reproduce on my internal network, if I try on mobile data the links and codes work fine.
- This is what I get in the console:
“The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.”
- Exemple of room and invite links: 
    - https://svtesthub.com/PhZdbuf/quiet-zigzag-camptest 
    - https://svtesthub.com/4dyg2gj/windy-cheery-huddle 
    - https://svtesthub.link/PhZdbuf
    - https://svtesthub.link/4dyg2gj 
- Attached a screenshot of the issue:
![forbidden](https://user-images.githubusercontent.com/93765706/143911178-76980e73-557e-4099-bc1b-f9dce270fa80.PNG)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1180)

**Comment by Softvision-RemusDranca** [comment] 2021-12-15 11:51
I was also able to reproduce this issue in multiple attempts using Windows 10 with Firefox and macOS with Safari. It seems that the ".com" and "/link" are added to the URL when accessed and when using the room code it displayed that the room is not found.
Considering this I will add a higher severity to this issue.
Attached is also a video of this issue:
![Forbidden](https://user-images.githubusercontent.com/40061643/146181539-f8e158a8-188f-46a8-a58d-d3633d858ca8.gif)

**Comment by netpro2k** [comment] 2022-01-06 01:54
Looking through the code I suspect this "Forbidden" message is coming from the rate limiting we added for security on guessing link codes. https://github.com/mozilla/reticulum/blob/f72e1cf7436c10c4d2751fb3c2eef28dde0fbe5a/lib/ret_web/fail2ban.ex#L5 

If you hit a link url more than twice in 2 seconds your ip will be banned (from going to link urls) for 2 hours. Its a bit inconsistent since you have to have hit the same reticulum server each time and only that server will ban you. Its pretty unlikely a user will do this on accident (to confirm this behavior I was trying to get myself banned and it was pretty difficult to do manually.

This also seems consistent with the behavior you were seeing with it being network (ip) specific. Closing this, if it turns out to be reproducible in some other way feel free to re-open.

**Closed by netpro2k** 2022-01-06 01:54 UTC
Labels: bug, needs triage, [QA]:Major-issue, jira-hubs, [QA]:Regression, HC-October-Release

**Comment by brianpeiris** [comment] 2022-01-06 21:14
I agree this doesn't seem like a blocker for this release, since it was triggered specifically by QA testing the link multiple times in quick succession. The rate-limit is tied to your IP, so it's unlikely that users will run into this in the real world, where users will have different IPs and are unlikely to open the same link within 2 seconds.
