### ISSUE TITLE
clarify in Privacy Notice how long data is stored for presence/comms + metrics/exceptions collected

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#327] opened 2018-04-27 04:19 UTC
in the [_Privacy Notice_](https://github.com/mozilla/hubs/blob/master/PRIVACY.md#things-you-should-know), under the two main bullet points, it'd be nice to specify for how long the data is stored. forever? until storage quota is exceeded? or until a specified TTL is met? can the expiry times/dates be modified by the user? any manual expungement/clearing by the Mozilla Hubs Ops team? etc.

**Comment by cvan** [comment] 2018-04-27 04:53
relevant: 
![screenshot 230](https://user-images.githubusercontent.com/203725/39345254-44d09f62-499c-11e8-908d-c2f363c4d969.png)

**Comment by gfodor** [comment] 2018-05-02 00:16
Do these privacy related issues belong in the legal docs repo? I don't think the resolution of this bug will impact code but just increase clarity on the notice. (FWIW we do not have any expiration/cleanup mechanisms in place, in part because of the minimal amount of data we collect.)

**Comment by misslivirose** [comment] 2019-07-22 23:55
I'm going to resolve this - we got additional clarity from legal about where timing should live and the media removal from Mozilla servers is explicitly specified in there. Given the changes to the notice since this was opened a year ago, we'd ask for new considerations to be filed as a new issue. Also, by design, closing the room should now only ever happen if the room owner explicitly closes it.

**Closed by misslivirose** 2019-07-22 23:55 UTC
Labels: meta
