### ISSUE TITLE
Avatar is hidden / invisible

### ISSUE THREAD

**Issue by ybinstock** [mozilla/hubs#3409] opened 2020-11-21 10:08 UTC
**Description**
In one of the rooms I've created, https://hubs.mozilla.com/3WuwDo9/hanukkah-room

I was testing it with two computers to have multiple avatars in the room. 

Even if I tried changing the avatars, I could only see each person's name and not their avatar. 

There were no errors in the console. 

I tested both on firefox and chrome. 

I don't know if the issue has to do with the room, something to do with the avatars, my browser/computer, or something else.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-493)

**Comment by Softvision-GeluHaiduc** [comment] 2020-11-23 09:37
I managed to reproduce this issue on Firefox Release 83.0 and Chrome 87.0.4280.66 on both Windows 10x64 and Ubuntu 18.04.2 using the same room as in the issue. The issue is not reproducible on other rooms or newly created rooms.

**Comment by ybinstock** [comment] 2020-11-24 08:22
Is there anything I can do to help you figure out the problem?

**Comment by misslivirose** [comment] 2020-12-07 19:16
This does not reproduce for me, but it took multiple attempts to load because performance in this scene is so memory-intensive. Even with a dedicated GPU I'm getting <23 fps with a single tab open. There are 76 textures in this room, 175k triangles, and 95 draw calls. This is 4x the recommended texture and polygon count, so I suspect that issues with loading in additional models is related directly to this scene.

**Comment by brianpeiris** [comment] 2022-09-08 12:25
Could not repro this either, and a lot has changed since this bug was filed, so I suspect any issue that might have existed has been fixed incidentally since it was reported.

**Closed by brianpeiris** 2022-09-08 12:25 UTC
Labels: jira-hubs
