### ISSUE TITLE
[Safari] The audio is broken on certain MacOS/Safari versions

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4411] opened 2021-07-14 12:37 UTC
**[Notes]:**
- The issue is reproducible when communicating with other users and also when playing spawned videos.
- The performance also seems to be affected.

**[Affected Versions]:**
- Safari - Version 14.1.1 (15611.2.7.1.6, 15611)

**[Affected Platforms]:**
- MacOS Catalina 10.15.7 (19H1217)

**[Prerequisites]:**
- Have a room opened on "https://hubs.mozilla.com/".

**[Steps to reproduce]:**
1. Spawn a video inside the room.
2. Play the video for a small period of time.
3. Observe the behavior.

**[Expected results]:**
- The video is correctly played.

**[Actual results]:**
- The audio is broken.

**[Additional Notes]:**
- I reproduced this issue using different scenes.
- I reproduced the issue when playing videos inside the room.
- I reproduced the issue on 3 different devices using the same version.
- According to statcounter macOS Catalina is the most used version for MacOS. 
- Could be related to #4288 
- Attached is a screen recording of the issue where you can see the performance being affected: [link](https://drive.google.com/file/d/1zaJW_Ubk3rqvwovLI-7k-32ZtHtEEyjG/view?usp=sharing).
- Here are the logs received while reproducing the issue: [link](https://drive.google.com/file/d/18KJ1s0aOSVV0hGCs0codMHhdI0EulMSH/view?usp=sharing).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBSOLD-72)

**Comment by Softvision-RemusDranca** [comment] 2021-07-14 14:36
I've encountered an additional behavior while testing. If for example a YouTube video is playing in a different tab, when focusing the Hubs tab the video's audio from the Youtube tab is broken.

**Comment by Softvision-RemusDranca** [comment] 2021-07-16 15:55
- I've managed to get some help from another team and they were also able to reproduce the issue using:
	- MacBook Pro macOS Big Sur Version 11.3.1 (20E241), Safari Version 14.1 (16611.1.21.161.6).
	- MacBook Pro macOS Big Sur Version 11.4 (20F71), Safari Version 14.1.1 (16611.2.7.1.4).
	- I was also able to reproduce the issue on Iphone SE 2 having OS Version 14.6, but the audio was not as cranky as on MacOS. [Here](https://drive.google.com/file/d/1Yj_RoFPWcfJYXn5aRTzE95jkavuQYPfN/view?usp=sharing) is a recording where you can see the video playing being interrupted.
- The sound was cranky after approximately a half of minute of playing media or communicating with others.
- I was only able to test on **MacBook Pro** devices, I could probably get some help with an iMac next week.

- On a different matter I also ran into some performance issues, on MacOS Catalina 10.15.7 (19H1217) using Safari Version 14.1.1 (15611.2.7.1.6, 15611). [Here](https://drive.google.com/file/d/1QulTiNk8lPYglXmXooyUHFjIDLPAV07r/view?usp=sharing) is a recording and also the console [logs](https://drive.google.com/file/d/13uOS92YcOmOW6HPuj3UdZQt_RnkMXaYl/view?usp=sharing). Not really sure if everything is connected but I could open a separate issue for this if necessary.

**Comment by takahirox** [comment] 2021-07-16 18:28
On my MacBook Pro, macOS Big Sur 11.4, Safari Version 14.1.1, I can reproduce the audio issue.

But I can't reproduce the performance issue. According to the console logs you shared, the shader compile fails and I speculate it's the cause. But I don't see shader compile error on my end. Could it be scene or object specific issue? Cab you create a scene and pin objects where you encounter the compile error and the performance issue?

**Comment by brianpeiris** [comment] 2021-07-18 15:34
I'd suggest we open a new issue for the performance problem.

**Comment by brianpeiris** [comment] 2021-07-18 16:26
I've reproduced the audio distortion issue consistently in Safari 14.1.1 on macOS (11.4 MacBook Air M1 2020) and iOS (14.6 iPhone 11). The issue reproduces at different rates in different environments, but it does happen eventually in all cases. The issue does not occur on Chrome or Firefox on macOS.
I've reproduced it with a simplified test case, using only WebAudio. The key factor is a PannerNode that updates it transform continuously. I've also posted my details in an existing webkit bug report: https://bugs.webkit.org/show_bug.cgi?id=227199
I think our only option for now is to disable spatial audio in Safari until this bug is fixed in the browser. We might emulate attenuated audio instead.

**Comment by takahirox** [comment] 2021-07-19 19:07
Nice investigation!

> I think our only option for now is to disable spatial audio in Safari until this bug is fixed in the browser. We might emulate attenuated audio instead.

I agree with it. Disabling spatial audio should be much better than broken audio.

Regarding the performance issue, I confirmed that CPU usage on Mac is very high even on [a simple Three.js positional audio example](https://threejs.org/examples/#webaudio_orientation) so I speculate the performance problem may be very relevant to the audio issue as @Softvision-RemusDranca mentioned.

@brianpeiris Did you already start to work on the workaround? If not and you don't have time, I can take it. I hope we add the workaround soon and test to check if the performance issue can be resolved.

**Comment by brianpeiris** [comment] 2021-07-23 11:13
#4442 Fixes avatar audio issues for the next Hubs Cloud release, but I'll have to deal with the current version of the code separately for HMC, since the new audio code is quite different.

**Comment by takahirox** [comment] 2021-08-09 21:20
I would like to try to apply the same change to `master`, just in case after an audio related PR #4487 will be merged, unless @brianpeiris wants to work on it because hubs.mozilla.com is very useless on MacOS/iOS Safari and very hard to even test on them now.

**Comment by brianpeiris** [comment] 2021-08-09 21:25
Go ahead @takahirox I'm going to continue focusing on Hubs Cloud.

**Comment by takahirox** [comment] 2021-08-10 21:42
OK, made a PR #4503

**Comment by takahirox** [comment] 2021-09-14 16:08
Regarding the Positional (Panner) audio bug, we thought it was a Safari specific bug but it seems that I can reproduce the problem even on iOS Chrome/Firefox. (I speculate iOS Safari/Chrome/Firefox use the same core webkit library?)

Currently we disable Positional audio for Safari but we may need to disable it for Safari or iOS.

Can anyone here check if you can reproduce the problem on iOS Chrome/Firefox on your end, too?

**Comment by johnshaughnessy** [comment] 2021-09-14 17:12
@takahirox If we can't diagnose and fix the root cause, I wonder if there's a workaround we can do where we disconnect from dialog, tear down all the voice connections, and then reconnect/recreate them every 5 minutes or so.

**Comment by takahirox** [comment] 2021-09-14 17:25
@johnshaughnessy It might be worth to try, although I'm not really sure if it can resolve the problem.

**Comment by takahirox** [comment] 2021-09-16 00:25
I made a simple test case.

https://github.com/takahirox/ios-webaudio-test

It plays music with or without WebAudio.

On my iOS 14.8, the audio with WebAudio is broken after about two minutes regardless of browsers (Safari/Chrome/Firefox) while the one without WebAudio isn't broken.

I'm going to report this problem to webkit bugzilla. (I guess all the major iOS browsers use the same webkit engine for WebAudio.)

WebAudio on iOS doesn't seem to be stable. I googled and found that WebAudio on iOS have repeatedly had bugs, fixed them, and had regression bugs again.

I'm thinking of avoiding to use WebAudio until iOS WebAudio will be matured enough.

A workaround in my mind is to add a new (Three.js) audio class which plays audio just with `audioElement.play()`, doesn't use WebAudio API, and is compatible with Three.js Audio API. It doesn't have panner, but has audio attenuation by controlling `audioElement.volume`.

**Comment by takahirox** [comment] 2021-09-25 03:11
(Finally!) I made a simple test case reproducing the crackle noise problem on iOS

https://takahirox.github.io/ios-webaudio-test/video_user_media.html

If you click "run" button on your iOS, you would hear crackled audio from the video.

A workaround seems to be disabling `echoCancellation` when creating user media for mic. If you uncheck `echoCancellation` in the test, you would notice that the crackle noise is reduced. (Somehow the noise is not perfectly removed on my iOS, but much better.)

I tried to disable `echoCancellation` in the preference on Hubs and confirmed that the audio becomes much better.

So, I would like to suggest to force to disable `echoCancellation` on iOS.

**Comment by takahirox** [comment] 2021-09-27 23:50
I discussed the crackle audio noise problem and we found that it might be old iPhone specific problem.

We don't have many enough iOS devices, so iOS users, can I ask for volunteers?

I'm happy if you run the test to check whether you can reproduce the problem I encountered, and report to me here whether you can reproduce or not.

1. Go to https://takahirox.github.io/ios-webaudio-test/video_user_media.html on your iOS device with Safari (and other browsers)
2. Every item is checked and press run button
3. You hear crackle noise from video audio
4. Reload the page, uncheck "echoCancellation", and press run button
5. You hear less noise

**Comment by jure** [comment] 2021-09-28 19:51
Data point for your latest test @takahirox.

On iOS 15 on an iPhone XS Max I hear no crackling with `echoCancellation` on or off - it does not make a difference.

**Comment by takahirox** [comment] 2021-09-29 01:29
@jure Thanks for the test. Your model is newer and more powerful than mine (iPhoneX) so I guess you didn't see the issue.

**Comment by Softvision-RemusDranca** [comment] 2021-09-29 14:13
@takahirox I have the same result as @jure , no crackling noise with or without  echoCancellation. I used Iphone SE2 with Safari 15.

**Comment by takahirox** [comment] 2021-09-29 19:14
Thanks all. 

I also asked for the test at different places and we tested some more iPhone devices.

The models on which the audio noise problem is reproducible
* iPhone 8+ (released in 2017)
* iPhoneX (released in 2017)

The models on which the audio noise problem isn't reproducible
* iPhone XS Max (released in 2018)
* iPhone11 (released in 2019)
* iPhone SE2 (released in 2020)

Sounds like only the problem reproducible only on old (2017 or before?) models (maybe meaning less powerful models). We couldn't find global iPhone model market share numbers, but I guess iPhone users generally use newer models?

So I don't think we should force to disable echo cancellation. (#4679)

We can share the tips with users instead

1. we suggest to upgrade iOS to iOS 15
2. if you still hear audio noise, we suggest to disable echo cancellation in the preference

**Comment by takahirox** [comment] 2021-09-29 19:16
@Softvision-RemusDranca 

Sounds like the broken audio issue shouldn't happen in iPhone SE 2 + iOS 15 and with the patches we recently applied. Do you mind if testing again to check if the problem is still reproducible?

**Comment by vincentfretin** [comment] 2021-09-30 09:26
No crackling with echoCancellation on or off with iPad 2018 6th gen iOS 14.8.

**Comment by Softvision-RemusDranca** [comment] 2021-10-04 14:25
@takahirox Unfortunately, I was able to reproduce the issue using Iphone SE2 after approximately ten minutes but it was only for a very short moment, after that the audio was working again. The issue reproduced while I was playing a video in the background and also having a conversation between two users.

**Comment by takahirox** [comment] 2021-10-04 19:02
@vincentfretin 

Thanks for testing. The problem doesn't seem to be occurred on iPad.

@Softvision-RemusDranca

It's good to know that at least it sounds better than before. But you couldn't reproduce the audio noise problem on https://takahirox.github.io/ios-webaudio-test/video_user_media.html but can still reproduce the noise problem on Hubs. Hm, there might be another issue or high resource usage may affect the audio quality.

I think it's hard to further investigate. I will report the problem to Apple devs so far.

**Comment by takahirox** [comment] 2021-10-04 21:12
Reported to https://bugs.webkit.org/show_bug.cgi?id=227199 Please post there if you have additional context.

**Comment by brianpeiris** [comment] 2022-04-08 23:48
Just to add more data points, I tested this today with my iPhone 11, running iOS 15.4 and Safari 15.4. I used two bots with movement and audio, and ran the test for 30 minutes. Audio did not distort or crackle. I guess this is primarily due to #4594. The Safari team may have also fixed some underlying issues, but we'd have to test with positional audio re-enabled to verify that.

I'd suggest we can close this bug, since it is not an issue for current models and the latest iOS/Safari. If it is still an issue on older iPhone models, and we care about fixing that issue, we can open a new ticket with up-to-date, summarized information about the issue.

**Comment by pigubaoza** [comment] 2022-05-25 04:51
hi i would like to check if positional audio is re-enabled? it looks like it's still disabled here https://github.com/mozilla/hubs/blob/fe4eb6ffbc94fb411f8d98754376aed7e0c2b01a/src/systems/sound-effects-system.js#L141
I have also filed an issue that I think might be related: https://github.com/mozilla/hubs/issues/5458

**Comment by takahirox** [comment] 2022-05-25 15:29
Thanks for the report.

OK, just in case let's test again and if the problem is not reproducible we can re-enable it.

**Comment by takahirox** [comment] 2022-05-25 20:19
Made a PR #5460

**Comment by takahirox** [comment] 2022-06-03 21:47
#5460 has been merged. Closing this issue. Please file a new issue if anyone encounters broken audio problem on Safari again.

Audio/Video noise problem seems to still exist. Let's track that issue in #4322

**Closed by takahirox** 2022-06-03 21:47 UTC
Labels: bug, P3, needs triage, ios, [QA]:Major-issue, jira-hubs, safari
