### ISSUE TITLE
Allow media owner to specify a "friendly" object name for items via the object menu

### ISSUE THREAD

**Issue by robin-k-wilson** [mozilla/hubs#3300] opened 2020-11-09 21:12 UTC
**Is your feature request related to a problem? Please describe.**
See discussion thread: https://github.com/mozilla/hubs/discussions/3156

> To show off 3D models on mobile, users have to go through the object browser, and many of the files end up with 'reticulum.io...6ee3f' as their names which is quite hard for people to understand and feel welcomed by.

**Describe the solution you'd like**
> Is there an option to display the filename instead of the link name? Showing something like 'Ancient Mummy 12BC.fbx' might be more user-friendly in some cases, if this is possible.

**Comment by misslivirose** [comment] 2020-11-13 15:34
This is something we've discussed for a while - this seems like a duplicate of #2300 with one proposed solution to improving the way that we utilize this data. I'm going to resolve this as a duplicate of #2300 and copy the information over to that so we're tracking it in a single issue.

**Closed by misslivirose** 2020-11-13 15:34 UTC
Labels: enhancement
