### ISSUE TITLE
Probleme to delete avatar in the admin panel

### ISSUE THREAD

**Issue by kazode** [mozilla/hubs#2564] opened 2020-06-12 01:19 UTC
**Description**
When we go in the admin panel for remove a avatar, the avatar is not deleting and we get delugged
**To Reproduce**
1. Go to 'admin panel'
2. Click on 'Avatar.'
3. Scroll down to any avatar and click on edit and delete
4. the avatar is not delete and we got logged out

**Expected behavior**
Does it a already know bug or just on our side?

**Hardware** 
 - Device: Macbook Pro 2019, and Surface pro 4
 - OS: [Windows and OS X
 - Browser Chrome, firefox, safari

**Comment by misslivirose** [comment] 2020-06-12 18:06
Thanks for filing this - this work is being tracked in the Hubs Cloud repo here: https://github.com/mozilla/hubs-cloud/issues/44

I'm going to resolve this as a duplicate of that one!

**Closed by misslivirose** 2020-06-12 18:06 UTC
Labels: bug, needs triage
