### ISSUE TITLE
Can't Close room with ' in the name

### ISSUE THREAD

**Issue by kk5dire** [mozilla/hubs#5330] opened 2022-04-03 22:29 UTC
**Description**
Room not letting me close it due to ' in the name, due to it thinking my typing in the name was incorrect 

**To Reproduce**
1. Go to 'https://hub.mozilla.com'
2. Click on 'Create room'
3. Click on 'options'
4. Change the name to something with a ' in it
5. Scroll down and click 'apply'
6. Attempt to close the room via the overflow menu
7.  Observe error

**Expected behavior**
The room should close as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/52354566/161451412-42ee8209-cacc-4e6a-b21c-d63ae3db8093.png)

**Hardware** 
 - Device: [Desktop]
 - OS: [Windows 11 Version 22H2 (Build 22581.200) eval copy 22581.ni_release.220318-1623]
 - Browser: [Microsoft Edge 100.0.1185.29 (Official build) (64-bit) ]

**Additional context**
This issue seems to be inconsistent depending on the connection.

**Comment by matthewbcool** [comment] 2022-04-12 17:30
Thanks very much for the detailed report. I was unable to reproduce. [edge, chrome, FF] MacOS
I tried:
changing the scene name using an ' and applying the change
closing the room by retyping the name in the confirm room name field.
![Screen Shot 2022-04-12 at 10 19 58 AM](https://user-images.githubusercontent.com/4493657/163020054-2dd79820-4d81-45b2-9ffb-62934fc3a814.png)
![Screen Shot 2022-04-12 at 10 20 18 AM](https://user-images.githubusercontent.com/4493657/163020057-5eb7d1d4-bbf3-4447-88ba-bee9ede7c0ec.png)
![Screen Shot 2022-04-12 at 10 21 32 AM](https://user-images.githubusercontent.com/4493657/163020059-21ae2049-0812-4d7b-b0b8-82717844eb04.png)

Let me know if I missed anything. Is it possible you have an extra space in the screenshot? I notice the cursor is outside the text field in the screenshot and I wonder if this is a windows edge specific quirk with the ui?

**Closed** 2022-04-26 14:16 UTC
Labels: bug, needs triage
