### ISSUE TITLE
Audio from other avatars delayed several seconds

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1687] opened 2019-08-21 19:08 UTC
**Description**
In standup today, I saw people's heads scaling very immediately after they talked in real life, but then I didn't actually hear their audio for several seconds later.

**To Reproduce**
Not sure.

**Expected behavior**
Audio should not be delayed

**Hardware** 
Desktop, linux, firefox

**Comment by johnshaughnessy** [comment] 2019-08-21 19:09
```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). ZbCT7XE:1:1
A-Frame Version: https://github.com/MozillaReality/aframe index.js:80
three Version: https://github.com/MozillaReality/three.js index.js:81
core:schema:warn Default value `null` does not match type `string` in component `media-loader` 2 browser.js:111
core:schema:warn Default value `null` does not match type `string` in component `player-info` browser.js:111
core:schema:warn Default value `null` does not match type `string` in component `camera-focus-button` browser.js:111
core:schema:warn Default value `null` does not match type `string` in component `emit-scene-event-on-remove` browser.js:111
Hubs version: 1027 (c355fb01960e06cbb6b226416007492c92fd4929) hub.js:4:8
Tracking: Sentry DSN: https://013d6a364fed43cdb0539a61d520597a@sentry.prod.mozaws.net/370 telemetry.js:10:12
Using WebGL 2.0 context. console.js:35
THREE.WebGLRenderer 106dev console.js:35
THREE.WebGLRenderer: WEBGL_multiview extension not supported. console.js:35
THREE.WebGLRenderer: OVR_multiview extension not supported. console.js:35
Using Non-VR bindings. console.js:35
Error: WebGL warning: copyTexSubImage3D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow. 8 WebGLAtlasTexture.js:406
Hub ID: ZbCT7XE console.js:35
Reticulum @ gallant-illusionist.reticulum.io: v1.0.20190820235422 on arbre console.js:35
Phoenix Socket URL: wss://gallant-illusionist.reticulum.io:443 console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
Logged into account 266429049016943454 console.js:35
Janus host: quirky-fighter.reticulum.io console.js:35
Scene URL: https://uploads-prod.reticulum.io/files/ac2864d0-d457-4829-826c-0d1fbd586131.glb console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
Avatar does not an 'allOpen' animation, disabling hand animations 2 console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
[three-pathfinding]: Use THREE.BufferGeometry, not THREE.Geometry, to create zone. console.js:35
traverseMeshesAndAddShapes physics-utils.js:59:12
collision not found in scene console.js:35
mesh contains high triangle density region console.js:35
mesh density exceeded, using floor plan only console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
Avatar does not an 'allOpen' animation, disabling hand animations 2 console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
Avatar does not an 'allOpen' animation, disabling hand animations 2 console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. 3 console.js:35
The MediaStream passed to createMediaStreamSource has a cross-origin resource, the node will output silence. networked-audio-source.js:60
body not found console.js:35
The MediaStream passed to createMediaStreamSource has a cross-origin resource, the node will output silence. networked-audio-source.js:60
THREE.WebGLRenderer: Texture marked for update but image is undefined 26 console.js:35
Source map error: TypeError: sketchfab-zip.worker-9ed027c28bd1d8e9e008.js.map is not a valid URL.
Resource URL: blob:https://hubs.mozilla.com/85b8bcb3-98ce-4e41-8146-59dab96abb62
Source Map URL: sketchfab-zip.worker-9ed027c28bd1d8e9e008.js.map

Source map error: TypeError: gifparsing.worker-7cba2e1c639db96ea898.js.map is not a valid URL.
Resource URL: blob:https://hubs.mozilla.com/0876db96-a0c3-4f49-bddc-7053833713b9
Source Map URL: gifparsing.worker-7cba2e1c639db96ea898.js.map

Using microphone: Plantronics .Audio 648 USB Analog Stereo console.js:35
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
Invalid URI. Load of media resource  failed. ZbCT7XE
Growing array to 5 console.js:35
Error: WebGL warning: copyTexSubImage3D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow. 10 WebGLAtlasTexture.js:204
Error: WebGL warning: copyTexSubImage3D: The specified TexImage has not yet been specified. WebGLAtlasTexture.js:406
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
Error: WebGL warning: copyTexSubImage3D: The specified TexImage has not yet been specified. WebGLAtlasTexture.js:406
Error: WebGL warning: copyTexSubImage3D: The specified TexImage has not yet been specified. WebGLAtlasTexture.js:406
THREE.GLTFLoader: Duplicating UVs to support aoMap. console.js:35
body not found 2 console.js:35
body not found console.js:35
entity registered with system despite being removed console.js:35
Invalid URI. Load of media resource  failed. ZbCT7XE
body not found 2 console.js:35
Error: WebGL warning: copyTexSubImage3D: The specified TexImage has not yet been specified. WebGLAtlasTexture.js:406
Error: WebGL warning: copyTexSubImage3D: The specified TexImage has not yet been specified. WebGLAtlasTexture.js:406
Error: WebGL warning: copyTexSubImage3D: The specified TexImage has not yet been specified. WebGLAtlasTexture.js:406
Error: WebGL warning: copyTexSubImage3D: The specified TexImage has not yet been specified. WebGLAtlasTexture.js:406
body not found 2 console.js:35
```

**Comment by misslivirose** [comment] 2019-08-22 16:39
Putting this as a P2 until we can get a confirmed repro, at which point I think that will be worth bumping to a P1 given that I'd imagine it's quite disruptive to the experience.

**Comment by misslivirose** [comment] 2020-03-23 14:46
@johnshaughnessy - would you be okay if we close this given it's age and lack of recent repro?

**Comment by joshmarinacci** [comment] 2020-07-17 19:58
closing

**Closed by joshmarinacci** 2020-07-17 19:58 UTC
Labels: P2, bug

**Comment by hamirmahal** [comment] 2021-03-23 20:41
**Description**
> I saw people's heads scaling very immediately after they talked in real life, but then I didn't actually hear their audio for several seconds later.

For me, an avatar's head actually scales at the same time I hear sound from them, as expected. However, like @johnshaughnessy, there's a definite audio delay. I'm able to confirm this by visiting the same Mozilla Hub VR room on a fast device, and a slow device, and listening to audio from both simultaneously. The fast device receives and plays the audio first, and then several milliseconds later I'll hear the audio and see the avatar head-scaling on the slower device.

**To Reproduce**
Visit a Mozilla Hub room with three people: A, B and C, with person C listening to a conversation between A and B simultaneously with two devices: a slow one and a fast one. Person C will need to play audio on both devices simultaneously as A and B converse.

**Expected behavior**
Audio should not be delayed. Or, maybe we can have a less-intensive version of Hubs for older devices? I think the audio delay on the older device is caused by its old hardware taking longer to process Mozilla Hubs. The device that has the audio delay has a `1.4 GHz Dual-Core Intel Core i5` processor.

**Hardware** 
Device that's experiencing the very noticeable audio delay: Desktop, macOS Big Sur Version 11.2.3, Safari Version 14.0.3 (16610.4.3.1.7)
