### ISSUE TITLE
Unable to access Hubs instances through Firefox Reality

### ISSUE THREAD

**Issue by Octavector** [mozilla/hubs#899] opened 2019-02-17 16:32 UTC
Using the default Oculus Go browser I am able to join Atrium and Medieval Fantasy Book rooms without issue.

When using Firefox Reality I experience a few different behaviours. With Atrium instances, the map loads however I appear unable to move and stuck within the "T" pose. The avatar's head also appears to be on the floor in the centre of the room and I am unable to interact with the environment.

![org mozilla vrbrowser-20190217-155307](https://user-images.githubusercontent.com/9148462/52915874-0f6f0b00-32d1-11e9-99ce-51af8c3f3a31.jpg)

When attempting to enter a Medieval Fantasy Book instance I only get as far as the loading spinner which does not stop or go.

![org mozilla vrbrowser-20190217-155438](https://user-images.githubusercontent.com/9148462/52915885-2f063380-32d1-11e9-8ff9-088b46e667de.jpg)

**Comment by cvan** [comment] 2019-04-11 08:46
I can reproduce: In Firefox Reality on both Oculus standalone headsets, I unable to enter VR in Hubs rooms. Also, the non-VR mode doesn't load or run correctly (page layout issues, transparency, various cosmetic/rendering issues, etc.).

![2019-04-04_16:51:50](https://user-images.githubusercontent.com/203725/55943445-763ae180-5bfb-11e9-92aa-afab2d1e468a.png)
![2019-04-04_16:53:22](https://user-images.githubusercontent.com/203725/55943444-75a24b00-5bfb-11e9-9150-c749b1ba797e.png)
![2019-04-04_16:53:33](https://user-images.githubusercontent.com/203725/55943442-75a24b00-5bfb-11e9-825d-8efed8c859c1.png)
![2019-04-04_16:54:57](https://user-images.githubusercontent.com/203725/55943441-75a24b00-5bfb-11e9-888a-e5c67cdc2015.png)

**Comment by ecsmyth** [comment] 2019-04-12 16:40
I'm also able to reproduce on the Oculus Go using FxR 1.1.3-31011915-oculusvr-arm64-release about 95% of the time. Issue presents for me in 2D and VR modes the same way as cvan described. I managed to get an Atrium room to load correctly once, but I haven't found repro steps to allow me to get in again. Rooms consistently load correctly in Oculus Browser.

**Comment by misslivirose** [comment] 2019-08-07 23:14
I am reproing this with the latest store version of FxR on Oculus Quest, but it only happens for me when I am creating a room, not when I'm joining an existing room.

**Comment by misslivirose** [comment] 2019-08-07 23:36
This seems to be related to scene changing - if you go through the standard path without changing anything, all is well. But if you try to change scenes when creating a new room, this seems to result in problems like the ones listed above.

**Comment by misslivirose** [comment] 2019-08-07 23:38
We should test the featured scenes and identify which ones of them don't work well on Quest.

**Comment by gfodor** [comment] 2019-08-23 01:05
this fix has now landed in FxR nightly

**Closed** 2019-08-23 18:01 UTC
Labels: P1, bug, user submitted
