### ISSUE TITLE
Spawned Text is cut off when using magic wand in chat

### ISSUE THREAD

**Issue by qiangjiadong** [mozilla/hubs#5661] opened 2022-08-18 10:12 UTC
**Description**
Sending any texts through Magic Wand feature in the chat box results in a wrong position of texts in the black background.

**To Reproduce**
1. Create room
2. Go to 'Chat', type anything,
3. Click on 'Magic Wand' button
5. See error in the room

**Expected behavior**
Texts being Magic Wand in the proper position.

**Screenshots**
![text bug](https://user-images.githubusercontent.com/37507397/185370789-c39585d5-b37a-4609-8b4d-946d77e651bc.jpg)

**Hardware** 
 - Device: [e.g. Desktop]
 - OS: [e.g. Windows 10]
 - Browser: [e.g. Chrome]

**Additional context**

**Comment by takahirox** [comment] 2022-08-29 18:17
Confirmed this bug on my windows 10 Chrome. I don't think I saw it before. Probably this may be a regression bug caused by some recent commits.

**Comment by emclaren** [comment] 2022-08-29 20:19
@netpro2k - just wondering if this could _possibly_ be related to some of the work you are doing on new entity system?

**Comment by matthewbcool** [comment] 2023-04-30 19:47
fixed with https://github.com/mozilla/hubs/pull/5836 https://github.com/mozilla/hubs/issues/5710

**Closed by matthewbcool** 2023-04-30 19:47 UTC
Labels: bug, needs triage
