### ISSUE TITLE
Hidden Audio file Bug

### ISSUE THREAD

**Issue by BonzoMartini** [mozilla/hubs#3349] opened 2020-11-16 16:18 UTC
**Description**

_When Audio file is not set to hidden it's sound plays at the correct (set) volume (in Hubs)
When the Audio file is set to hidden, the sound plays at around 5% of the set volume (in Hubs)_

**To Reproduce**

_Add audio file, set hidden_

**Expected behavior**

_What I want is audio in my scene, without showing an icon. - this happens in _Spoke_ when you press play -the icon disappears.
The 'hidden' checkbox should disable the icon, not affect the sound volume._

**Screenshots**

**Hardware** 
_PC, Windows, Firefox, Oper_a

**Additional context**

 _(Silent is to Sound. What Hidden is to Visible)_

**Comment by misslivirose** [comment] 2020-11-19 14:11
Thanks for filing! The root cause seems to have been identified in #3392 that the sound is actually playing from the origin instead of it's location. Resolving this one as a duplicate of 3392 so we can track the fix on a single issue.

**Closed by misslivirose** 2020-11-19 14:11 UTC
Labels: bug, needs triage

**Comment by BonzoMartini** [comment] 2020-11-19 14:13
When do you guesstimate a fix? (was hoping to use positional sound for an event next week)

**Comment by johnshaughnessy** [comment] 2020-11-19 16:39
Darn, I thought I fixed this issue back in October. Did I miss something?
https://github.com/mozilla/hubs/pull/3121
